import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const source = await readFile("src/app/egzersizler/mental-aritmetik/MentalArithmeticGameClient.tsx", "utf8");
const css = await readFile("src/app/egzersizler/mental-aritmetik/mentalArithmetic.module.css", "utf8");
const targetSource = await readFile("src/app/egzersizler/mental-aritmetik/TargetTotalGameClient.tsx", "utf8");
const targetCss = await readFile("src/app/egzersizler/mental-aritmetik/targetTotalGame.module.css", "utf8");
const chainSource = await readFile("src/app/egzersizler/mental-aritmetik/ChainOperationGameClient.tsx", "utf8");
const chainCss = await readFile("src/app/egzersizler/mental-aritmetik/chainOperationGame.module.css", "utf8");
const chainLogic = await readFile("src/lib/exercises/chainOperation.ts", "utf8");
const cashSource = await readFile("src/app/egzersizler/mental-aritmetik/CashRegisterGameClient.tsx", "utf8");
const cashCss = await readFile("src/app/egzersizler/mental-aritmetik/cashRegisterGame.module.css", "utf8");
const cashLogic = await readFile("src/lib/exercises/cashRegister.ts", "utf8");
const vaultSource = await readFile("src/app/egzersizler/mental-aritmetik/VaultGameClient.tsx", "utf8");
const vaultCss = await readFile("src/app/egzersizler/mental-aritmetik/vaultGame.module.css", "utf8");
const vaultLogic = await readFile("src/lib/exercises/vault.ts", "utf8");

assert.match(source, /ChainOperationGameClient/);
assert.match(chainLogic, /milliseconds: 1800/);
assert.match(chainLogic, /milliseconds: 1200/);
assert.match(chainLogic, /milliseconds: 800/);
assert.match(chainLogic, /CHAIN_OPERATION_MIN_START_MS = 1300/);
assert.match(chainLogic, /CHAIN_OPERATION_ANSWER_DELAY_MS = 350/);
assert.match(chainSource, /setActiveStep\(index\)/);
assert.match(chainSource, /getChainOperationProgress\(index \+ 1/);
assert.match(chainSource, /phase === "answer" &&/);
assert.match(source, /CashRegisterGameClient/);
assert.match(cashSource, /mode === "shopping"/);
assert.match(cashSource, /Sepet Toplamı/);
assert.match(cashSource, /Sen hesapla/);
assert.match(cashSource, /mode === "change"/);
assert.match(cashSource, /disabled=\{answered \|\| mode === "change"\}/);
assert.match(cashLogic, /CASH_REGISTER_CATALOG/);
assert.match(cashLogic, /CASH_REGISTER_PAYMENT_OPTIONS/);
assert.match(source, /TargetTotalGameClient/);
assert.match(targetSource, /Doğru kombinasyon/);
assert.match(targetSource, /feedback\?\.good/);
assert.match(targetSource, /Cevapla/);
assert.match(targetCss, /\.numberCardSolution/);
assert.match(targetCss, /\.scoreRing/);
assert.match(css, /\.marketLayout/);
assert.match(css, /\.receipt/);
assert.match(chainCss, /\.focusBox/);
assert.match(chainCss, /\.answerArea/);
assert.match(chainCss, /@media\(prefers-reduced-motion: reduce\)/);
assert.match(css, /@keyframes vaultShake/);
assert.match(css, /@keyframes scoreRise/);
assert.match(cashCss, /\.modeCard/);
assert.match(cashCss, /\.selectedProduct/);
assert.match(cashCss, /\.receiptTotal/);
assert.match(cashCss, /@media\(prefers-reduced-motion:reduce\)/);

console.log("mental arithmetic prototype parity checks passed");

assert.match(source, /VaultGameClient/);
assert.match(vaultLogic, /VAULT_LEVEL_CONFIG/);
assert.match(vaultLogic, /VAULT_DIGITS/);
assert.match(vaultLogic, /VAULT_TIMES/);
assert.match(vaultLogic, /VAULT_TOTAL_ROUNDS = 10/);
for (const type of ["twoStepHard", "divAdd", "mulSub", "sequence", "reverse", "digitLogic"]) assert.match(vaultLogic, new RegExp(type));
assert.match(vaultLogic, /Math\.pow\(ratio, \.72\)/);
assert.match(vaultSource, /inputMode="numeric"/);
assert.match(vaultSource, /event\.key === "Enter"/);
assert.match(vaultSource, /Backspace/);
assert.match(vaultSource, /Temizle/);
assert.match(vaultSource, /KASAYI A/);
assert.match(vaultSource, /saveExerciseResultSecure/);
assert.match(vaultSource, /submissionKey: `mental-mental-arithmetic-vault-/);
assert.match(vaultSource, /href="\/sonuc"/);
assert.match(vaultCss, /\.vaultOpen/);
assert.match(vaultCss, /\.correctFlash/);
assert.match(vaultCss, /\.wrongShake/);
assert.match(vaultCss, /@media\(max-width:800px\)/);
assert.match(vaultCss, /@media\(max-width:480px\)/);
assert.match(vaultCss, /prefers-reduced-motion:reduce/);
