import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { validateQuestionInput } from "../src/lib/paragraph-exercises/paragraphQuestionAdminRepository.ts";
const good = { category: "main_idea", difficulty: "medium", gradeBand: "6-7", passage: "Bilgi veren ve yeterli uzunlukta örnek paragraf metni.", question: "Paragrafın ana düşüncesi nedir?", options: ["Birinci seçenek", "İkinci seçenek", "Üçüncü seçenek", "Dördüncü seçenek", "Beşinci seçenek"], correctIndex: 0, explanation: "Açıklama metni burada yer alır." };
const gen = await readFile("src/app/api/admin/paragraph-questions/generate/route.ts", "utf8");
const save = await readFile("src/app/api/admin/paragraph-questions/ai-save/route.ts", "utf8");
const ui = await readFile("src/app/ogretmen/icerik-yonetimi/paragraf-sorulari/ParagraphQuestionAIGenerator.tsx", "utf8");
test("generate and ai-save require admin auth and keep secrets server-side", () => { assert.match(gen, /isAdminSessionValid/); assert.match(save, /isAdminSessionValid/); assert.doesNotMatch(ui, /OPENAI_API_KEY|SUPABASE_SERVICE_ROLE/); assert.match(gen, /OPENAI_API_KEY/); });
test("request limits and model fallback exist", () => { assert.match(gen, /questionCount.*10/); assert.match(gen, /questionCount.*1/); assert.match(gen, /topic\.length\s*>\s*160/); assert.match(gen, /customInstruction\.length\s*>\s*500/); assert.match(gen, /OPENAI_CONTENT_MODEL.*OPENAI_ANALYSIS_MODEL/); });
for (const [name, patch] of [["four options", { options: good.options.slice(0, 4) }], ["six options", { options: [...good.options, "alt"] }], ["duplicate option", { options: ["aynı", "aynı", "üç", "dört", "beş"] }], ["empty passage", { passage: "" }], ["empty question", { question: "" }], ["bad index", { correctIndex: 7 }], ["missing explanation", { explanation: "" }]]) test(`AI output ${name} rejected by shared validator`, () => assert.equal(validateQuestionInput({ ...good, ...patch }).ok, false));
test("structured schema and five-option contract", () => { assert.match(gen, /json_schema/); assert.match(gen, /minItems:\s*5/); assert.match(gen, /maximum:\s*4/); assert.match(gen, /correctIndex/); });
test("category prompt rules and answer diversity exist", () => { for (const text of ["Bütün paragrafı ölç", "Destekleyici ayrıntıyı ölç", "birebir yazılı olmasın", "anlam akışını tamamlasın", "Beş numaralı cümle", "Doğru indeksleri 0-4 arasında dengeli dağıt"]) assert.match(gen, new RegExp(text)); });
test("duplicate normalization and save-time recheck exist", () => { assert.match(gen, /normalize\("NFKC"\)/); assert.match(gen, /duplicateFlags/); assert.match(save, /normalize\("NFKC"\)/); assert.match(save, /status:409/); });
test("AI save revalidates, forces ai source and passive default", () => { assert.match(save, /validateQuestionInput/); assert.match(save, /createQuestion\(\{\.\.\.v\.value,isActive:body\.isActive===true\},"ai"\)/); });
test("retry is bounded and concurrency is process-local", () => { assert.equal((gen.match(/await call\(o/g) || []).length, 2); assert.match(gen, /active\.has/); assert.match(gen, /finally/); });
test("preview supports save and remove actions", () => { assert.match(ui, /Bu Soruyu Kaydet/); assert.match(ui, /Çıkar/); assert.match(ui, /duplicateFlags/); });
