import test from "node:test";
import assert from "node:assert/strict";
import { buildParagraphAnalysis, getParagraphQuestionCategory, PARAGRAPH_ANALYSIS_MIN_SAMPLE } from "../src/lib/paragraph-exercises/paragraphAnalysis.ts";
import { paragraphQuestions } from "../src/lib/paragraph-exercises/paragraphQuestions.ts";
import { readFile } from "node:fs/promises";

const answer = (index, correct = true, time = 30000) => ({ questionId: paragraphQuestions[index].id, correct, responseTimeMs: time });
const result = (id, date, answers, extra = {}) => ({ id, date, exerciseType: "paragraph", correctCount: answers.filter((item) => item.correct).length, wrongCount: answers.filter((item) => !item.correct).length, successRate: answers.length ? answers.filter((item) => item.correct).length / answers.length * 100 : 0, details: { answers, ...extra } });

test("boş veri güvenli empty state üretir", () => { const analysis = buildParagraphAnalysis([]); assert.equal(analysis.overall.completedSessions, 0); assert.equal(analysis.overall.accuracy, null); assert.equal(analysis.strongestCategory, null); assert.equal(analysis.trend.status, "insufficient"); });
test("tek session overall ve süreyi hesaplar", () => { const analysis = buildParagraphAnalysis([result("one", "2026-09-10T10:00:00Z", [answer(0, true, 1000), answer(1, false, 3000)])]); assert.equal(analysis.overall.answeredQuestions, 2); assert.equal(analysis.overall.correct, 1); assert.equal(analysis.overall.accuracy, 50); assert.equal(analysis.overall.averageResponseTimeMs, 2000); });
test("question metadata category lookup tek source kullanır", () => { assert.equal(getParagraphQuestionCategory(paragraphQuestions[0].id), "main_idea"); assert.equal(getParagraphQuestionCategory("missing"), null); });
test("kategori grouping ve minimum örnek eşiği çalışır", () => { const answers = Array.from({ length: PARAGRAPH_ANALYSIS_MIN_SAMPLE }, (_, index) => answer(index, index !== 0, 1000 + index)); const analysis = buildParagraphAnalysis([result("group", "2026-09-10T10:00:00Z", answers)]); const main = analysis.categories.find((item) => item.category === "main_idea"); assert.equal(main.answeredQuestions, 5); assert.equal(main.correct, 4); assert.equal(main.accuracy, 80); assert.equal(main.hasEnoughData, true); });
test("strongest ve needs-improvement eşitlikte deterministic seçilir", () => { const answers = [...Array.from({ length: 5 }, (_, index) => answer(index, true)), ...Array.from({ length: 5 }, (_, index) => answer(12 + index, false))]; const analysis = buildParagraphAnalysis([result("tie", "2026-09-10T10:00:00Z", answers)]); assert.equal(analysis.strongestCategory.category, "main_idea"); assert.equal(analysis.needsImprovementCategory.category, "supporting_idea"); });
test("eksik veya malformed answers kategori hesabına girmez", () => { const analysis = buildParagraphAnalysis([result("partial", "2026-09-10T10:00:00Z", [answer(0), { questionId: "bad" }, { questionId: paragraphQuestions[1].id, correct: true, responseTimeMs: 0 }])]); assert.equal(analysis.overall.answeredQuestions, 1); assert.equal(analysis.categories.find((item) => item.category === "main_idea").answeredQuestions, 1); });
test("sessionlar newest-first ve trend improving/declining hesaplanır", () => { const sessions = Array.from({ length: 6 }, (_, index) => result(String(index), `2026-09-${String(index + 1).padStart(2, "0")}T10:00:00Z`, [answer(index, index >= 3)])); const improving = buildParagraphAnalysis(sessions); assert.equal(improving.sessions[0].id, "5"); assert.equal(improving.trend.status, "improving"); const declining = buildParagraphAnalysis(sessions.map((item, index) => ({ ...item, successRate: index < 3 ? 100 : 0, details: { answers: [answer(index, index < 3)] } }))); assert.equal(declining.trend.status, "declining"); });
test("UI empty state, KPI, kategori ve son çalışmalar bölümlerini içerir", async () => { const client = await readFile(new URL("../src/components/teacher-panel/TeacherParagraphAnalysis.tsx", import.meta.url), "utf8"); for (const text of ["Henüz paragraf çalışması bulunmuyor", "Çözülen Soru", "Tamamlanan Çalışma", "Güçlü Alan", "Geliştirilmesi Gereken Alan", "Son Çalışmalar"]) assert.match(client, new RegExp(text)); });
