export type ParagraphCategory = "main_idea" | "supporting_idea" | "inference" | "completion" | "flow";
export type ParagraphQuestion = { id: string; category: ParagraphCategory; level: "easy" | "medium" | "hard"; gradeBand: "4-5" | "6-7" | "8" | "high-school"; paragraph: string; question: string; options: [string, string, string, string, string]; correctIndex: number; explanation: string };
type Row = [string, string, [string, string, string, string, string], number, ParagraphQuestion["level"], string];
const make = (category: ParagraphCategory, prefix: string, rows: Row[]): ParagraphQuestion[] => rows.map((row, index) => {
  const options = [...row[2]];
  const [correct] = options.splice(row[3], 1);
  const offset = { main_idea: 0, supporting_idea: 2, inference: 4, completion: 1, flow: 3 }[category];
  const targetIndex = (index + offset) % 5;
  options.splice(targetIndex, 0, correct);
  const qualifiers = [" Metindeki temel ilişkiye göre yanıtlayınız.", " Parçanın verdiği bilgilere göre düşününüz.", " Doğru seçeneği metnin bütünüyle karşılaştırınız.", " Anlatılan durumun sonucunu dikkate alınız.", " Metindeki ayrıntıları birlikte değerlendiriniz.", " Yazarın vurgusunu göz önünde bulundurunuz.", " Cevabınızı metindeki kanıtlara dayandırınız.", " Ana bağlantıyı ve yardımcı bilgileri ayırınız.", " Paragrafın anlam akışını izleyiniz.", " Verilen bilgilerden hareket ediniz.", " Metnin amacıyla uyumlu seçeneği bulunuz.", " Soruyu parçanın tamamını düşünerek yanıtlayınız."];
  return { id: `${prefix}-${String(index + 1).padStart(2, "0")}`, category, gradeBand: "6-7", paragraph: row[0], question: `${row[1]}${qualifiers[index]}`, options: options as [string, string, string, string, string], correctIndex: targetIndex, level: row[4], explanation: row[5] };
});

const mainIdea: Row[] = [
["Bir kitabı bitirdiğimizde yalnızca olayları öğrenmiş olmayız. Farklı kişilerin kararlarını düşünür, kendi hayatımızla karşılaştırmalar yaparız. Bu yüzden düzenli okuma, kelime bilgisinin yanında yorumlama becerisini de geliştirir.","Bu paragrafın ana düşüncesi nedir?",["Düzenli okuma, farklı zihinsel becerileri birlikte geliştirir.","Her kitap gerçek bir olay anlatır.","Okurlar yalnızca kelime öğrenir.","Kitap kahramanları doğru karar verir.","Okuma süresi bütün öğrenciler için aynıdır."],0,"easy","Paragraf hem kelime bilgisini hem de yorumlamayı birlikte vurguluyor; doğru cevap iki sonucu kapsıyor."],
["Okul bahçesine dikilen ağaçlar birkaç yıl içinde gölge vermeye başladı. Öğrenciler teneffüslerde bu alanlarda dinlenirken bahçedeki kuşları ve böcekleri de gözlemledi. Küçük bir düzenleme, okulun kullanımını ve canlı çeşitliliğini değiştirdi.","Parçanın temel düşüncesi hangisidir?",["Ağaçlar yalnızca gölge sağlar.","Yeşil alanlar okul yaşamını ve çevredeki canlıları olumlu etkiler.","Öğrenciler teneffüste gözlem yapamaz.","Böcekler okul bahçelerine zarar verir.","Ağaçların büyümesi birkaç gün sürer."],1,"easy","İkinci seçenek gölge, dinlenme ve canlı gözlemi sonuçlarını birlikte açıklayarak parçanın tamamını kapsar."],
["Bir hedef belirlemek, ne yapacağımızı bilmemizi sağlar; fakat hedefe ulaşmak için yöntemi de planlamak gerekir. Örneğin sınava hazırlanan bir öğrenci konuları günlere böler ve ilerlemesini düzenli aralıklarla kontrol eder.","Yazarın asıl vurgusu nedir?",["Her sınav aynı yöntemle kazanılır.","Hedefler yalnızca yazılı olarak tutulmalıdır.","Başarı için hedefi uygulanabilir bir planla desteklemek gerekir.","Konular son gün çalışılmalıdır.","İlerleme kontrolü zaman kaybıdır."],2,"easy","Metin hedef koymayı tek başına yeterli görmüyor; hedefin plan ve kontrolle desteklenmesini savunuyor."],
["Kentlerde bisiklet yollarının artması, kısa mesafelerde otomobil kullanımını azaltabilir. İnsanlar daha fazla hareket ederken sokaklardaki gürültü ve hava kirliliği de azalır. Böylece ulaşım tercihi, şehirdeki yaşam kalitesini etkiler.","Bu parçanın ana fikri nedir?",["Bisiklet yalnızca sporcular içindir.","Otomobiller bütün şehirlerde yasaklanmalıdır.","Bisiklet yolları yalnızca trafiği düzenler.","Bisiklet ulaşımı, şehir yaşamına çevresel ve sağlık açısından katkı sağlar.","Hava kirliliğinin tek nedeni ulaşımdır."],3,"medium","D seçeneği ulaşımın hareket, gürültü, hava ve yaşam kalitesi üzerindeki birlikte etkisini özetler."],
["Bir müzik eserini dinlerken yalnızca melodiyi değil, kullanılan çalgıların birbirine nasıl eşlik ettiğini de fark edebiliriz. Dikkatli dinleme, eserin neden hüzünlü, neşeli ya da hareketli hissettirdiğini anlamayı kolaylaştırır.","Paragrafın ana düşüncesi hangisidir?",["Her müzik eseri aynı duyguyu verir.","Çalgıların sayısı eserin değerini belirler.","Melodi müzikte önemsizdir.","Hüzünlü eserler daha iyi çalınır.","Dikkatli dinlemek, müziğin yapısını ve duygusunu anlamayı sağlar."],4,"medium","Parça, melodinin ötesindeki eşlikleri fark etmenin eserin duygusunu anlamaya yardım ettiğini anlatıyor."],
["Bir mahalledeki paylaşım dolabı, kullanılmayan eşyaların çöpe gitmesini önlemek için kurulmuştu. İhtiyacı olmayanlar temiz eşyalarını bırakıyor, ihtiyacı olanlar da bunları ücretsiz alıyordu. Zamanla dolap, komşular arasında güven ve dayanışma oluşturdu.","Bu paragrafta anlatılmak istenen nedir?",["Eşyalar yalnızca satın alınmalıdır.","Paylaşım uygulamaları hem israfı azaltır hem de dayanışmayı güçlendirir.","Komşular birbirinden eşya almamalıdır.","Dolapların bakımı imkânsızdır.","İsraf yalnızca evlerde görülür."],1,"medium","İkinci seçenek hem israfın azalmasını hem de komşuluk dayanışmasını birlikte karşılıyor."],
["Bir deneyin sonucunu önceden tahmin etmek, öğrenciyi gözlem yapmaya hazırlar. Tahmin doğru çıkmasa bile öğrenci hangi düşüncesinin değiştiğini fark eder ve yeni kanıtlar üzerinden daha dikkatli bir açıklama kurar.","Parçanın ana fikri nedir?",["Deneylerde yalnızca doğru tahminler önemlidir.","Bilimsel çalışmalarda açıklama yapmak gereksizdir.","Tahminler, doğru çıkmasa bile öğrenme ve düşünme sürecini destekler.","Öğrenciler deney sonucunu değiştirebilir.","Kanıtlar yalnızca öğretmenler için gereklidir."],2,"medium","Metin tahminin değerini sonucunun doğruluğuna değil, gözlem ve yeniden düşünme sürecine bağlıyor."],
["Bir fotoğrafın etkileyici olması için pahalı bir makineye sahip olmak şart değildir. Işığın yönünü gözlemek, uygun anı beklemek ve görüntüdeki gereksiz ayrıntıları ayıklamak çoğu zaman daha belirleyicidir.","Yazarın vurguladığı ana düşünce nedir?",["Pahalı makineler her fotoğrafı güzelleştirir.","Fotoğraf çekmek için yalnızca hızlı davranmak gerekir.","Işık fotoğrafçılıkta önemsizdir.","İyi fotoğraf, araçtan çok dikkat ve doğru seçimlerle oluşur.","Fotoğrafta ayrıntı ne kadar fazlaysa sonuç o kadar iyidir."],3,"medium","D seçeneği, araçtan bağımsız olarak ışık, zamanlama ve kadraj seçimlerinin önemini topluyor."],
["Kıyıya bırakılan plastikler dalgalarla denize taşınabiliyor. Bu atıklar bazı canlılar tarafından yiyecek sanılıyor ve beslenme düzenlerini bozuyor. Sahili temiz tutmak, yalnızca güzel bir görüntü oluşturmak değil, deniz canlılarını korumak anlamına da geliyor.","Bu paragrafın ana fikri hangisidir?",["Sahil temizliği deniz canlılarının sağlığı için de gereklidir.","Plastikler yalnızca kıyıda kalır.","Deniz canlıları plastikleri kolayca ayırt eder.","Güzel bir sahil her zaman temizdir.","Dalgalar kıyıya zarar vermez."],0,"hard","İlk seçenek, plastiklerin canlılara etkisi ile sahil temizliği arasındaki temel bağlantıyı kuruyor."],
["Bir şehrin müzeleri, geçmişte yaşamış insanların kullandığı eşyaları korur. Ziyaretçi bu eşyaların hangi koşullarda kullanıldığını öğrendiğinde tarih, ezberlenecek tarihler listesinden çıkar ve günlük hayatla ilişkilenen canlı bir bilgiye dönüşür.","Parçanın temel düşüncesi nedir?",["Müzeler yalnızca eski eşya depolarıdır.","Tarih öğrenmek için bütün eşyalar satın alınmalıdır.","Müzeler, geçmişi günlük yaşamla ilişkilendirerek anlamayı kolaylaştırır.","Ziyaretçiler müzelerde konuşmamalıdır.","Tarihte yalnızca önemli kişiler incelenir."],2,"hard","C seçeneği, müzelerin eşyalar aracılığıyla tarihi günlük hayatla ilişkilendirme işlevini açıklıyor."],
["Bir ekipte herkesin aynı fikirde olması, işlerin mutlaka iyi gideceği anlamına gelmez. Farklı öneriler dikkatle dinlendiğinde eksik noktalar görünür hâle gelir; önemli olan tartışmayı kişilere değil, çözüme yöneltmektir.","Paragrafın ana mesajı nedir?",["Ekiplerde tartışma olmamalıdır.","Farklı fikirler yapıcı biçimde değerlendirildiğinde ekip çalışmasını güçlendirir.","Aynı fikirde olmayan kişiler ekipten ayrılmalıdır.","Çözüm üretmek yalnızca yöneticinin görevidir.","İyi ekiplerde herkes aynı düşünür."],1,"hard","Metin, görüş ayrılığını sorun olarak değil, çözüm odaklı yürütüldüğünde eksikleri gösteren bir imkân olarak sunuyor."],
["Bir alışkanlığı değiştirmek isteyen kişi, yalnızca kendine ‘artık yapmayacağım’ demekle yetinmeyebilir. Eski davranışı başlatan ortamı fark etmek, yerine küçük bir alternatif koymak ve ilerlemeyi takip etmek değişimi daha sürdürülebilir hâle getirir.","Bu paragrafın ana düşüncesi nedir?",["Alışkanlıklar bir günde değişir.","İrade kullanmak alışkanlık değişiminde gereksizdir.","Bütün alışkanlıklar aynı yöntemle bırakılır.","İlerlemeyi takip etmek değişimi zorlaştırır.","Alışkanlık değişimi, nedenleri fark edip uygulanabilir adımlar atmayı gerektirir."],4,"easy","E seçeneği, ortamı fark etme, alternatif koyma ve takip etme adımlarını birlikte özetliyor."],
];

const supporting: Row[] = [
["Okulda kurulan tohum takas köşesinde öğrenciler, yetiştirdikleri bitkilerden kalan tohumları küçük zarflara koydu. Zarfların üzerine bitkinin adı, ekim zamanı ve güneş ihtiyacı yazıldı. Böylece öğrenciler yalnızca tohum değil, deneyim de paylaşmış oldu.","Parçada aşağıdakilerden hangisine değinilmiştir?",["Zarflara bitkilerin bakım bilgileri yazılmıştır.","Tohumların tamamı öğretmenler tarafından toplanmıştır.","Öğrenciler yalnızca çiçek yetiştirmiştir.","Takas köşesi yıl boyunca kapalı kalmıştır.","Bitkiler güneşsiz yetiştirilmiştir."],0,"easy","İlk seçenek metinde açıkça verilen bakım bilgilerini doğru aktarır; diğerleri parçayla uyuşmaz."],
["Bir öğrenci sunum hazırlarken önce güvenilir kaynakları inceledi, sonra önemli bilgileri kendi cümleleriyle not aldı. Sunum sırasında kullandığı kaynakların adını da belirtti. Bu çalışma, araştırmanın yalnızca bilgi toplamaktan ibaret olmadığını gösterdi.","Parçada aşağıdakilerden hangisi söylenmektedir?",["Sunumda kaynak belirtmek gereksizdir.","Bilgileri kendi cümleleriyle düzenlemek araştırma sürecinin bir parçasıdır.","Öğrenci hiçbir kaynak kullanmamıştır.","Sunum hazırlamak yalnızca ezber yapmayı gerektirir.","Güvenilir kaynaklar araştırmayı zorlaştırır."],1,"easy","B seçeneği, öğrencinin bilgileri kendi cümleleriyle not almasını doğrudan karşılıyor."],
["Parktaki yağmur bahçesinde, suyu toprağa geçiren özel bitkiler yetiştiriliyordu. Şiddetli yağmurdan sonra suyun bir bölümü burada tutuluyor, sokaklardaki birikinti azalıyordu. Bahçıvanlar bu alanın düzenli bakım istediğini özellikle belirtiyordu.","Bu parçadan hangisine ulaşılabilir?",["Yağmur bahçeleri hiç bakım istemez.","Bu alanlar yalnızca süs amacıyla kurulmuştur.","Yağmur bahçeleri su birikintilerini azaltmaya yardımcı olabilir.","Özel bitkiler yağmurda yaşayamaz.","Sokaklardaki bütün su bu alanlarda toplanır."],2,"medium","C seçeneği, yağmur suyunun bir bölümünün tutulması ile sokaktaki birikintinin azalması arasındaki sonucu kurar."],
["Bir sınıfta öğrenciler, kullanılmayan kâğıtları iki yüzünü de kullanmak üzere ayrı bir kutuda biriktirdi. Kutunun yanına tek yüzü boş kâğıtların taslak çalışmalarında kullanılabileceği yazıldı. Bir ay sonunda yeni kâğıt tüketiminin azaldığı görüldü.","Parçadan aşağıdakilerden hangisi çıkarılamaz?",["Kâğıdın iki yüzünü kullanmak tüketimi azaltabilir.","Taslak çalışmaları için kullanılmış kâğıtlardan yararlanılmıştır.","Sınıf, kâğıtları yeniden değerlendirmek için bir yöntem uygulamıştır.","Bir ay sonunda bütün kâğıt kullanımı tamamen bitmiştir.","Kutunun yanında kullanım amacı açıklanmıştır."],3,"medium","D seçeneği çıkarılamaz; metin tüketimin azaldığını söylüyor, tamamen bittiğini söylemiyor."],
["Mert, okul çıkışında arkadaşının çantasının yırtıldığını fark etti. Kendi yedek ipini verdi ve çantayı birlikte onardılar. Ertesi gün arkadaşı ipi geri getirirken yanında küçük bir not da bıraktı.","Parçada aşağıdakilerden hangisine değinilmiştir?",["Mert çantayı tek başına satın almıştır.","İki arkadaş bir sorunu birlikte çözmüştür.","Not, çantanın içine saklanmıştır.","Arkadaşlar okuldan önce buluşmuştur.","Yedek ip kullanılmamıştır."],1,"medium","İkinci seçenek, ip verme ve çantayı birlikte onarma ayrıntılarını doğru birleştiriyor."],
["Bir şehir kütüphanesi, sınav haftasında sessiz çalışma saatlerini uzattı. Ayrıca masaların yanına prizler ve su sebilleri yerleştirdi. Öğrenciler, özellikle akşam saatlerinde bu düzenlemeden yararlandı.","Bu parçadan hangisi çıkarılabilir?",["Kütüphane sınav haftasında tamamen kapanmıştır.","Öğrenciler yalnızca sabahları çalışmıştır.","Çalışma ortamındaki küçük düzenlemeler öğrencilerin kullanımını artırabilir.","Su sebilleri kitap okumayı engeller.","Kütüphanelerde priz bulunamaz."],2,"medium","C seçeneği, uzatılan saatler ve eklenen imkânların öğrencilerin kullanımını artırdığı sonucunu çıkarır."],
["Bir doğa gözlem kulübü, her hafta aynı gölün kıyısında farklı kuşları kaydetti. Öğrenciler gözlemlerini fotoğrafla destekledi ve tarihleri not etti. Dönem sonunda hangi kuşların hangi aylarda görüldüğüne dair bir çizelge hazırladılar.","Parçada aşağıdakilerden hangisi söylenmektedir?",["Gözlemler tek bir gün yapılmıştır.","Kuşların fotoğrafı çekilmemiştir.","Kulüp yalnızca gölün suyunu incelemiştir.","Öğrenciler gözlemlerden yararlanarak dönem sonunda çizelge oluşturmuştur.","Kuşlar her ay aynı sayıda görülmüştür."],3,"medium","D seçeneği, tarihli gözlemlerden dönem sonu çizelgesi hazırlanması bilgisini doğru verir."],
["Bir öğrenci, matematik sorularında yaptığı hataları küçük bir deftere yazmaya başladı. Hatanın nedenini ve doğru çözümde hangi adımın değiştiğini de ekledi. Birkaç hafta sonra benzer sorularda aynı yanlışı daha az yaptığını fark etti.","Bu parçadan hangisine ulaşılabilir?",["Hatalar yazıldığında bütün sorular kolaylaşır.","Öğrenci matematik çalışmayı bırakmıştır.","Hataları incelemek, benzer yanlışları azaltmaya yardımcı olabilir.","Doğru çözümde hiçbir adım değişmez.","Defter yalnızca öğretmen için tutulmuştur."],2,"hard","C seçeneği, hata nedenlerini inceleme ile benzer yanlışların azalması arasındaki gözlenebilir sonucu açıklar."],
["Mahalledeki yaşlı bir komşu, eski oyunları çocuklara öğretmek için hafta sonu buluşmaları düzenledi. Çocuklar oyunların kurallarını öğrenirken komşuları da kendi çocukluğundan anılar anlattı. Buluşmalar, farklı yaş gruplarını aynı etkinlikte bir araya getirdi.","Parçadan aşağıdakilerden hangisi çıkarılamaz?",["Buluşmalar farklı yaşları bir araya getirmiştir.","Çocuklar eski oyunların kurallarını öğrenmiştir.","Komşu, çocukluğuna ait anılar paylaşmıştır.","Etkinlik yalnızca yetişkinlerin katılımına açıktır.","Buluşmalar hafta sonu yapılmıştır."],3,"hard","D seçeneği çıkarılamaz; metin çocukların da etkinlikte bulunduğunu açıkça gösteriyor."],
["Bir okul koridoruna öğrencilerin sorularını yazabileceği bir pano asıldı. Öğretmenler her hafta bu sorulardan birkaçını seçip kısa cevaplar ekledi. Zamanla öğrenciler, ders sırasında akıllarına gelen soruları ertelemeden yazmaya başladı.","Parçada aşağıdakilerden hangisine değinilmiştir?",["Soruların tamamı aynı gün cevaplanmıştır.","Pano, öğrencilerin merak ettikleri konuları görünür kılmıştır.","Öğretmenler öğrencilerin sorularını toplamıştır.","Öğrenciler ders sırasında hiç soru sormamıştır.","Pano yalnızca duyurular için kullanılmıştır."],1,"easy","B seçeneği, öğrencilerin sorularını yazması ve meraklarını görünür hâle getirmesi ayrıntısına dayanır."],
["Bir spor kulübü, antrenman sonrasında oyuncuların yalnızca skorlarını değil, birbirlerine yaptıkları destekleri de değerlendirdi. Böylece savunmada arkadaşını uyaran ya da hata yapan arkadaşını cesaretlendiren oyuncular fark edildi.","Bu parçadan hangisine ulaşılabilir?",["Kulüp yalnızca kazanan oyuncuları önemser.","Skorlar antrenmandan sonra hiç konuşulmaz.","Takım içindeki olumlu davranışlar da performansın değerlendirilmesinde dikkate alınabilir.","Oyuncular birbirleriyle iletişim kuramaz.","Savunma çalışmaları gereksizdir."],2,"hard","C seçeneği, skor dışındaki destek davranışlarının ayrıca değerlendirildiği bilgisinden çıkarılır."],
["Bir öğrenci, şehirdeki tarihi binaları fotoğraflarken her binanın yapım tarihini ve kullanım amacını araştırdı. Fotoğrafları tek başına sergilemek yerine kısa bilgi kartlarıyla birlikte sundu. Böylece ziyaretçiler binaları yalnızca görüntüleriyle değil, öyküleriyle de tanıdı.","Parçada aşağıdakilerden hangisi söylenmektedir?",["Fotoğraflarda bilgi kartı kullanılmamıştır.","Binaların yalnızca dış görünüşü incelenmiştir.","Öğrenci hiçbir araştırma yapmamıştır.","Ziyaretçiler sergiyi görmemiştir.","Fotoğraflar, araştırma bilgileriyle desteklenerek sunulmuştur."],4,"easy","E seçeneği, fotoğrafların yapım tarihi ve kullanım bilgileriyle birlikte sunulmasını karşılıyor."],
];

const inference: Row[] = [
["Ece, ödev yaparken telefonunu çalışma masasından kaldırıp salondaki çekmeceye koyuyor. Masasına yalnızca gerekli kitapları getiriyor ve çalışmaya başlamadan önce yapacağı işleri kâğıda yazıyor.","Bu parçadan Ece ile ilgili hangi sonuca ulaşılabilir?",["Ece ödev yapmayı sevmemektedir.","Ece, dikkatini korumak için çalışma ortamını düzenlemektedir.","Ece bütün ödevlerini telefondan yapmaktadır.","Ece plansız çalışmayı tercih etmektedir.","Ece yalnızca salonda ders çalışır."],1,"easy","Telefonu uzaklaştırması, gerekli eşyaları seçmesi ve işlerini yazması Ece’nin dikkatini korumaya çalıştığını gösterir."],
["Arda, yağmur başlamadan önce balkonundaki saksıları duvarın altına çekti. Sonra toprağın çok ıslanıp ıslanmadığını kontrol etti ve pencereyi kapattı. Yağmur dindikten sonra bitkileri yeniden güneş alan yere koydu.","Bu parçadan Arda'nın hangi davranışı çıkarılabilir?",["Bitkileriyle hiç ilgilenmemektedir.","Yağmurda dışarı çıkmayı sevmektedir.","Bitkilerin hava koşullarından zarar görmemesi için önlem almaktadır.","Saksıları tamamen kaldırmıştır.","Bitkilerin güneşe ihtiyacı olmadığını düşünmektedir."],2,"easy","Saksıları korunaklı yere çekmesi ve sonrasında yeniden yerleştirmesi, bitkileri hava koşullarına göre koruduğunu gösterir."],
["Kulüp toplantısında herkes kendi önerisini anlattı. Deniz, arkadaşının fikrindeki eksik noktayı gösterirken önce onun güçlü yanını belirtti, sonra birlikte geliştirebilecekleri bir yol önerdi. Toplantı sonunda iki öneri birleştirildi.","Deniz'in iletişim biçimiyle ilgili hangi çıkarım yapılabilir?",["Eleştiriden kaçınmaktadır.","Yalnızca kendi fikrinin kabul edilmesini istemektedir.","Farklı görüşleri yapıcı biçimde geliştirmeye çalışmaktadır.","Toplantılarda konuşmamaktadır.","Arkadaşının fikrini tamamen reddetmiştir."],2,"medium","Güçlü yanı belirtip eksik noktaya çözüm önermesi, Deniz’in eleştiriyi geliştirme amacıyla yaptığını gösterir."],
["Köydeki değirmenin yanında yıllardır duran taş oluğun içinden artık su akmıyordu. Çocuklar oluğun yukarısındaki kanalın yapraklarla dolduğunu fark etti. Kanal temizlenince su yeniden oluğa ulaştı.","Parçadan hangi sonuca ulaşılabilir?",["Değirmen tamamen yıkılmıştır.","Taş oluk su taşımak için kullanılmaktadır.","Çocuklar kanalı kullanmamıştır.","Yapraklar suyun akışını engellemiş olabilir.","Su kaynağı kurumuştur."],3,"medium","Kanal temizlenince suyun geri gelmesi, akışın yapraklar tarafından engellenmiş olabileceğini düşündürür."],
["Selin, arkadaşının doğum günü için hazırladığı resmi son anda değiştirmedi. Çünkü arkadaşının sade çizimleri sevdiğini biliyor ve resmi kendi beğenisine göre süslemek istemiyordu. Hediyeyi verirken arkadaşının yorumunu dikkatle dinledi.","Selin'in tutumuyla ilgili hangisi çıkarılabilir?",["Arkadaşının zevkine saygı göstermektedir.","Resim yapmayı sevmemektedir.","Hediyesini değiştirmeyi unutmuştur.","Kendi beğenisini herkesinkinden üstün görmektedir.","Arkadaşının yorumunu önemsememektedir."],0,"medium","Resmi değiştirmemesi ve arkadaşının yorumunu dinlemesi, onun zevkine saygı duyduğunu gösterir."],
["Bir gölün çevresindeki kurbağa sesleri önceki yıllara göre azalmıştı. Öğrenciler suyun kenarında deterjan köpükleri gördü ve yakındaki atölyeden gelen giderin göle ulaştığını öğrendi. Gider kapatılıp kıyı temizlenince kurbağaların sayısı zamanla arttı.","Bu parçadan hangi sonuca ulaşılabilir?",["Kurbağalar yalnızca geceleri yaşar.","Göl çevresindeki sesler ölçülememiştir.","Su kirliliği kurbağaların yaşamını olumsuz etkilemiş olabilir.","Atölye gölden çok uzaktadır.","Kurbağaların sayısı kıyı temizliğiyle azalır."],2,"medium","Köpüklerin görülmesi, giderin kapatılması ve kurbağaların artması su kirliliği ile yaşam arasındaki bağlantıyı düşündürür."],
["Yusuf, grup çalışmasında zorlandığı bölümü arkadaşlarından saklamadı. Önce soruyu nasıl anladığını anlattı, sonra arkadaşlarının farklı çözüm yollarını karşılaştırdı. Sonunda kendi yöntemindeki eksik adımı fark edip çözümünü düzeltti.","Yusuf hakkında aşağıdakilerden hangisi çıkarılabilir?",["Yardım istemeyi başarısızlık saymaktadır.","Grup çalışmasında yalnız kalmayı tercih etmektedir.","Hatasını fark ettiğinde düşüncesini gözden geçirebilmektedir.","Sadece kendi çözümünün doğru olduğuna inanır.","Soruyu arkadaşlarına çözdürmüştür."],2,"medium","Farklı yöntemleri karşılaştırıp eksik adımını düzeltmesi, Yusuf’un geri bildirime açık olduğunu gösterir."],
["Bir kasabanın meydanındaki saat uzun zamandır çalışmıyordu. Belediye görevlileri saati onarmak için eski parçaları araştırırken meydanda toplanan kişiler kendi anılarını anlattı. Saat yeniden çalıştığında insanlar yalnızca zamanı değil, meydanın ortak geçmişini de hatırladı.","Bu parçadan hangi sonuca ulaşılabilir?",["Saatin hiçbir tarihî değeri yoktur.","Meydan yalnızca görevliler tarafından kullanılır.","Eski bir eşya, insanlar arasında ortak anıların canlanmasını sağlayabilir.","İnsanlar saat çalışırken meydana gelmemiştir.","Saatin parçaları hiç araştırılmamıştır."],2,"hard","Onarım sırasında anıların paylaşılması, saatin ortak geçmişi hatırlatan bir sembol olduğunu düşündürür."],
["Nehir kıyısındaki köprüden geçenler, korkuluğun bazı bölümlerinin paslandığını fark etti. Mahalle sakinleri fotoğraf çekip belediyeye bildirdi, ardından onarım tamamlanana kadar çocukların köprüye yalnız gitmemesi konusunda anlaştı.","Mahalle sakinleriyle ilgili hangi çıkarım yapılabilir?",["Sorunu fark edip hem bildirim hem de geçici güvenlik önlemi almışlardır.","Köprünün onarılmasını istememişlerdir.","Çocukların köprüden geçmesini teşvik etmişlerdir.","Paslanan bölümleri kendileri sökmüştür.","Köprüde hiç tehlike görmemişlerdir."],0,"hard","Fotoğrafla bildirim yapılması ve çocuklar için geçici kural konması, sakinlerin sorumlu davrandığını gösterir."],
["Nisa, her sabah aynı otobüse biniyor ancak bir gün şoförün durakta bekleyen yaşlı bir yolcuyu fark ettiğini gördü. Şoför kapıyı kapatmak yerine birkaç saniye daha bekledi. Nisa, küçük bir dikkatin birinin yolculuğunu kolaylaştırabileceğini düşündü.","Nisa'nın düşüncesinden hangi sonuç çıkarılabilir?",["Otobüsler her zaman geç kalır.","Şoför yaşlı yolcuyu tanımaktadır.","Nisa toplu taşımayı kullanmayı bırakmıştır.","Küçük bir özenli davranışın başkasına önemli kolaylık sağlayabileceğini düşünmektedir.","Yaşlı yolcu otobüse binememiştir."],3,"easy","Nisa’nın düşüncesi, şoförün birkaç saniyelik dikkatinin yolcunun işini kolaylaştırmasına dayanıyor."],
["Bir bilim insanı, deneyinde beklediği sonucu elde edemedi. Verileri silmek yerine ölçüm araçlarını ve deney koşullarını yeniden kontrol etti. Daha sonra ilk tahmininin yanlış olduğunu kabul ederek yeni bir soru oluşturdu.","Bilim insanının tutumuyla ilgili hangi çıkarım yapılabilir?",["Başarısız sonucu gizlemeyi seçmiştir.","Sonuçları önceden değiştirmiştir.","Kanıtlarla karşılaşınca düşüncesini yeniden değerlendirebilmektedir.","Yeni soru sormayı gereksiz bulmaktadır.","Deney yapmaktan vazgeçmiştir."],2,"hard","Verileri koruması, koşulları kontrol etmesi ve tahminini değiştirmesi bilimsel tutarlılık gösterir."],
["İrem, hafta boyunca kullanmadığı eşyaları bir kutuda biriktirdi. Hafta sonunda kutudaki eşyaları ‘başkasına yarayabilir’, ‘onarılabilir’ ve ‘dönüştürülebilir’ diye ayırdı. Kutudan çıkanların çoğunu çöpe atmak yerine farklı biçimlerde değerlendirdi.","İrem'in davranışından hangi sonuca ulaşılabilir?",["Eşyalarını sınıflandırmadan atmaktadır.","Tüketim kararlarının sonuçlarını düşünerek israfı azaltmaya çalışmaktadır.","Hiçbir eşyayı kullanmamaktadır.","Onarılabilecek eşyaları çöpe göndermektedir.","Dönüştürmeyi gereksiz görmektedir."],1,"easy","Eşyaları kullanım durumuna göre ayırması, İrem’in atıkların sonucunu düşünüp israfı azaltmaya çalıştığını gösterir."],
];

const completion: Row[] = [
["Bir öğrenci, sabahları çantasına hangi kitapları koyacağını akşamdan belirlemeye başladı. Böylece aceleyle hazırlanırken defterlerini evde unutma sorunu azaldı. _____","Paragraf aşağıdakilerden hangisiyle tamamlanırsa anlam bütünlüğü sağlanır?",["Önceden yapılan küçük hazırlıklar, güne daha düzenli başlamaya yardım eder.","Bu nedenle bütün kitaplar aynı anda okunmalıdır.","Çantalar yalnızca okulda hazırlanır.","Unutmak her öğrencinin değişmez özelliğidir.","Sabahları hazırlık yapmak her zaman daha uzun sürer."],0,"easy","Son cümle, akşamdan yapılan hazırlığın unutmayı azaltmasıyla bağ kurup genel sonucu çıkarıyor."],
["Mahalledeki boş arsa, yıllarca yalnızca toz ve taşlarla kaplıydı. Sakinler burada küçük bir oyun alanı yapmak için belediyeye başvurdu ve ağaç dikme planı hazırladı. _____","Bu paragraf hangi cümleyle tamamlanmalıdır?",["Arsa daha sonra yine kullanılmadan bırakıldı.","Çocuklar oyun alanlarının hepsini sevmez.","Ortak bir istek, kullanılmayan bir alanın mahalle için yararlı hâle gelmesini sağlayabilir.","Ağaçların çoğu yalnızca ormanda yetişir.","Belediye başvurulara hiçbir zaman cevap vermez."],2,"easy","Yeni cümle, sakinlerin başvuru ve planından beklenen sonucu doğal biçimde tamamlıyor."],
["Bir müzik grubunda herkes aynı anda çalmaya çalışınca ortaya karmaşık bir ses çıktı. Öğretmen, her öğrencinin eser içindeki görevini belirledi ve dinleme işaretleri ekledi. _____","Paragrafın devamı aşağıdakilerden hangisi olmalıdır?",["Böylece grup, birbirini dinleyerek daha uyumlu çalmaya başladı.","Bütün öğrenciler müzik aletlerini bıraktı.","Eserin adı hiçbir zaman öğrenilmedi.","Dinleme işaretleri yalnızca resimlerde kullanılır.","Grup çalışmaları tek başına yapılır."],0,"easy","Görev paylaşımı ve dinleme işaretlerinin doğal sonucu, grubun daha uyumlu çalmasıdır."],
["Bir sınıf, gezide gördüğü tarihi yapılar hakkında kısa bilgi kartları hazırladı. Kartlarda yapının adı, yaşı ve dikkat çeken özelliği yer aldı. Ziyaretçiler kartları okuyarak yapıları daha kolay tanıdı. _____","Paragraf aşağıdakilerden hangisiyle tamamlanır?",["Bilgi kartları yapıların fotoğrafını yok etti.","Bu çalışma, geziyi yalnızca görmekten çıkarıp araştırmaya dayalı bir öğrenmeye dönüştürdü.","Tarihi yapılar artık hiç ziyaret edilmedi.","Öğrenciler kartları evde sakladı.","Gezilerde bilgi kullanmak gereksizdir."],1,"medium","Son cümle, kart hazırlama ve ziyaretçilerin öğrenmesi arasındaki eğitimsel sonucu tamamlıyor."],
["Bir aile, evdeki kullanılmayan kavanozları atmak yerine temizleyip mutfakta yeniden kullanmaya başladı. Kavanozların üzerine içindeki ürünün adı ve tarihi yazıldı. _____","Bu paragraf aşağıdakilerden hangisiyle tamamlanırsa anlam bütünlüğü sağlanır?",["Kavanozlar yalnızca süs eşyası olarak kaldı.","Böylece hem yeni kap alma ihtiyacı azaldı hem de düzen sağlandı.","Mutfakta hiçbir ürün saklanamaz.","Etiketler kavanozların kullanımını engelledi.","Aile bütün eşyalarını çöpe attı."],1,"medium","Yeniden kullanım ve etiketleme, ihtiyaç azaltma ve düzen sonucuna bağlanıyor."],
["Bir öğrenci, yazdığı öykünün ilk taslağını arkadaşına okuttu. Arkadaşı olayların bir bölümünün hızlı geçtiğini ve bazı kişilerin neden karar verdiğinin anlaşılmadığını söyledi. Öğrenci taslağı yeniden düzenledi. _____","Paragrafın son cümlesi hangisi olmalıdır?",["Bu geri bildirim, öykünün olay ve karakter bağlantılarını güçlendirdi.","Öykülerde karakterlerin kararları önemli değildir.","Arkadaşının önerileri metnin okunmasını zorlaştırdı.","İlk taslak her zaman son hâlden iyidir.","Öykü yeniden okunmadan yayımlandı."],0,"medium","Sorunların belirtilmesi ve metnin yeniden düzenlenmesi, bağlantıların güçlenmesi sonucunu doğurur."],
["Okulun su sebillerinin yanında öğrencileri kendi mataralarını getirmeye teşvik eden bir duyuru asıldı. Bir süre sonra sınıflarda tek kullanımlık bardakların azaldığı görüldü. _____","Paragraf aşağıdakilerden hangisiyle tamamlanmalıdır?",["Mataralar yalnızca spor salonunda kullanılır.","Duyurular hiçbir davranışı etkileyemez.","Küçük bir hatırlatma, çevreye yönelik bir alışkanlığın yayılmasına katkı sağlayabilir.","Bardakların sayısı bütün okullarda aynıdır.","Sebiller kullanılmadan kaldırıldı."],2,"medium","Duyuru ile bardak kullanımındaki azalma arasındaki ilişki, davranış alışkanlığındaki değişimi tamamlıyor."],
["Bir kasaba, yağmur suyu depolamak için evlerin çatılarından gelen suyu ortak bir depoda biriktirmeye başladı. Depodaki su bahçe sulamada kullanıldı; içme suyu ise ayrı tutuldu. _____","Bu paragrafın anlam bütünlüğünü sağlayan cümle hangisidir?",["Böylece içme suyunu gereksiz yere bahçe sulamada kullanma ihtiyacı azaldı.","Kasabada bütün çatılar kaldırıldı.","Bahçe sulamak artık tamamen yasaklandı.","Yağmur suyu her durumda içilebilir.","Depo yalnızca kışın boş kaldı."],0,"hard","İçme suyunun ayrı tutulması, depolanan suyun bahçe için kullanılmasıyla kaynak tasarrufu sonucuna bağlanır."],
["Bir öğrenci, yeni öğrendiği yabancı kelimeleri yalnızca liste hâlinde ezberlemek yerine kendi cümlelerinde kullanmaya başladı. Bazı cümleleri arkadaşlarıyla konuşurken tekrar etti. _____","Paragraf aşağıdakilerden hangisiyle tamamlanır?",["Kelimeler konuşmada hiç kullanılmadı.","Bu yöntem, kelimelerin anlamını bağlam içinde hatırlamasını kolaylaştırdı.","Yabancı dil öğrenmek yalnızca sözlüğe bakmaktır.","Arkadaşları cümleleri anlamadı.","Kelime listeleri tamamen kaldırıldı."],1,"hard","Kelimeyi cümlede ve konuşmada kullanmak, anlamı bağlama bağlayarak hatırlamayı kolaylaştırır."],
["Bir tiyatro kulübü oyunun dekorunu hazırlarken karton kutuları, eski kumaşları ve kullanılmayan boyaları değerlendirdi. Öğrenciler önce sahnenin ihtiyaçlarını listeledi, sonra ellerindeki malzemeleri bu listeye göre seçti. _____","Bu paragraf hangi cümleyle tamamlanmalıdır?",["Dekor çalışması plansız biçimde yarıda kaldı.","Böylece hem malzeme israfını azalttılar hem de yaratıcı bir dekor oluşturdular.","Tiyatroda dekor kullanmak yasaktır.","Eski kumaşlar hiçbir işe yaramadı.","Öğrenciler oyunu sahnesiz oynadı."],1,"hard","İhtiyaç listesiyle malzeme seçmek, hem israfı azaltan hem yaratıcı üretimi destekleyen sonuca götürüyor."],
["Bir okul, teneffüslerde koridorların çok gürültülü olduğunu fark etti. Öğrencilerle birlikte sessiz alanlar belirledi ve bu alanların kullanım kurallarını panoya astı. _____","Paragrafın sonuna hangisi getirilmelidir?",["Kuralların açıklanması, öğrencilerin farklı ihtiyaçlara göre alan seçmesini kolaylaştırdı.","Bütün öğrenciler teneffüslerde sınıfta kaldı.","Gürültü sorununu çözmek için bütün panolar kaldırıldı.","Sessiz alanlarda konuşmak tamamen yasaklandı.","Koridorlar artık hiç kullanılmadı."],0,"easy","Sessiz alanların belirlenmesi ve kuralların açıklanması, alan seçimini kolaylaştıran sonuca bağlanır."],
["Bir çocuk, balkonunda gördüğü kelebeklerin hangi bitkilerin çevresinde daha çok bulunduğunu not etti. Birkaç hafta sonra bazı bitkilerin kelebekleri çektiğini fark etti ve gözlemlerini çizimlerle destekledi. _____","Paragraf aşağıdakilerden hangisiyle tamamlanmalıdır?",["Gözlemlerini bırakıp bütün bitkileri söktü.","Kelebeklerin bitkilerle hiçbir ilişkisi yoktu.","Bu çalışma, merakın düzenli gözlemle küçük bir araştırmaya dönüşebileceğini gösterdi.","Çizimler gözlem yapmayı engelledi.","Çocuk yalnızca kelebeklerin rengini sordu."],2,"medium","Not alma, karşılaştırma ve çizim yapma adımları gözlemin küçük bir araştırmaya dönüştüğünü gösterir."],
];

const flow: Row[] = [
["(I) Okulun bahçesine yeni banklar yerleştirildi. (II) Öğrenciler teneffüslerde bu banklarda kitap okumaya başladı. (III) Bankların çevresine gölge sağlayan fidanlar dikildi. (IV) Kış aylarında bazı bölgelerde kar yağışı görülebilir. (V) Böylece bahçede dinlenmek için daha kullanışlı alanlar oluştu.","Akışı bozan cümle hangisidir?",["I","II","III","IV","V"],3,"easy","IV. cümle kar yağışından söz ederek bahçedeki bank ve fidanların işlevini anlatan akışı kesiyor."],
["(I) Bir araştırmacı önce gözlemlemek istediği canlıyı belirledi. (II) Gözlem saatlerini ve kullanacağı araçları planladı. (III) Araştırma defterinin kapağını mavi renge boyadı. (IV) Her gözlemden sonra bulgularını tarihleriyle yazdı. (V) Dönem sonunda notlarını karşılaştırarak bir sonuca ulaştı.","Numaralanmış cümlelerden hangisi düşünce akışını bozmaktadır?",["I","II","III","IV","V"],2,"easy","III. cümle defterin kapağının rengini anlatıyor; diğer cümleler araştırma sürecinin adımlarını izliyor."],
["(I) Mahalle sakinleri boş arsayı temizledi. (II) Alana sebze yetiştirmek için bölümler ayırdılar. (III) Her bölümden sorumlu kişiyi belirlediler. (IV) Mahalledeki apartmanların çoğu dört katlıdır. (V) Ürünleri ihtiyaç sahipleriyle paylaşmaya karar verdiler.","Akışı bozan cümle hangisidir?",["I","II","III","IV","V"],3,"easy","IV. cümle apartmanların kat sayısını vererek ortak bahçe kurma sürecinin dışına çıkıyor."],
["(I) Bir öğrenci sunumuna başlık ve amaç bilgisiyle başladı. (II) Konuyu destekleyen görseller kullandı. (III) Sunumdan sonra sınıftaki perdeler yıkandı. (IV) Önemli noktaları kısa cümlelerle açıkladı. (V) Sonunda dinleyicilerin sorularını yanıtladı.","Paragrafın akışını bozan cümle hangisidir?",["I","II","III","IV","V"],2,"medium","III. cümle sınıf perdesinin yıkanmasını anlatıyor; diğerleri sunumun hazırlanması ve yapılmasıyla ilgili."],
["(I) Arılar çiçeklerden nektar toplar. (II) Topladıkları nektarı kovana taşırlar. (III) Kovandaki bazı arılar nektarı işler. (IV) Balın tadı, tüketildiği ülkeye göre değişebilir. (V) Böylece koloni için besin depolanır.","Paragrafın akışını bozan cümle hangisidir?",["I","II","III","IV","V"],3,"medium","IV. cümle balın tadını ülkeler üzerinden anlatıyor; diğer cümleler arıların nektar işleme sürecini açıklıyor."],
["(I) Bir müzisyen yeni parçayı önce yavaş tempoda çaldı. (II) Zorlandığı ölçüleri ayrı ayrı tekrar etti. (III) Konser salonunun koltukları kırmızı renkteydi. (IV) Hataları azaldıkça tempoyu artırdı. (V) Son provada parçayı baştan sona çalmayı denedi.","Numaralı cümlelerden hangisi akışı bozmaktadır?",["I","II","III","IV","V"],2,"medium","III. cümle salonun koltuk rengini veriyor; diğer cümleler parçayı öğrenme aşamalarını anlatıyor."],
["(I) Bir kasaba, eski tren istasyonunu kültür merkezine dönüştürdü. (II) Bekleme salonunda yerel sanatçıların eserleri sergilendi. (III) İstasyonun çatısı iki yıl önce yenilenmişti. (IV) Eski bilet gişesi okuma köşesi olarak düzenlendi. (V) Böylece yapı hem korundu hem de halka açık yeni bir işlev kazandı.","Akışı bozan cümle hangisidir?",["I","II","III","IV","V"],2,"medium","III. cümle çatının geçmişte yenilenmesini söylüyor; diğerleri kültür merkezine dönüşümün yeni işlevlerini sıralıyor."],
["(I) Öğrenciler okul gezisi için yanlarına su mataraları aldı. (II) Öğretmen gezi boyunca çöplerin ayrı toplanmasını istedi. (III) Öğrenciler yürüyüş sırasında farklı ağaç türlerini gözlemledi. (IV) Okulun spor salonu geçen yıl boyandı. (V) Dönüşte herkes getirdiği atığı uygun kutuya bıraktı.","Düşünce akışını bozan cümle hangisidir?",["I","II","III","IV","V"],3,"hard","IV. cümle spor salonunun boyanmasını anlatıyor; diğerleri doğa gezisindeki çevre davranışlarıyla bağlantılı."],
["(I) Bir yazar karakterinin kararlarını belirlemeden önce onun geçmişini düşündü. (II) Karakterin korkularını ve hedeflerini not aldı. (III) Romanın ilk baskısı küçük bir yayınevinde yapılmıştı. (IV) Daha sonra olay örgüsünü bu özelliklere göre kurdu. (V) Böylece karakterin davranışları metin boyunca tutarlı kaldı.","Paragrafın akışını bozan cümle hangisidir?",["I","II","III","IV","V"],2,"hard","III. cümle romanın yayınevi bilgisini veriyor; diğerleri karakter oluşturma ve tutarlılıkla ilgili."],
["(I) Bir öğrenci sabah yapacağı işleri akşamdan listeledi. (II) Öncelikli işlerinin yanına küçük bir işaret koydu. (III) Çalışma masasının ahşap yüzeyini bezle sildi. (IV) Sabah ilk olarak öncelikli işine başladı. (V) Gün sonunda tamamladıklarını kontrol etti.","Akışı bozan cümle hangisidir?",["I","II","III","IV","V"],2,"easy","III. cümle masa temizliğini anlatıyor; diğerleri zaman planlama ve takip adımlarını sürdürüyor."],
["(I) Bir veteriner, barınaktaki köpeklerin davranışlarını gözlemledi. (II) Korkak olanların yanına önce sessizce oturdu. (III) Bazı köpeklerin tüyleri kahverengi ve beyazdı. (IV) Zamanla köpekler veterinerin yaklaşımına alıştı. (V) Daha sonra onları yeni ailelerle tanıştırmak kolaylaştı.","Numaralı cümlelerden hangisi akışı bozmaktadır?",["I","II","III","IV","V"],2,"hard","III. cümle tüy renklerini söylüyor; diğerleri veterinerin güven oluşturma sürecini anlatıyor."],
["(I) Bir ekip, okul gazetesi için röportaj konusu seçti. (II) Sorularını konuğun yaşına ve deneyimine uygun hazırladı. (III) Gazetenin son sayısında spor haberleri daha geniş yer tuttu. (IV) Röportaj sırasında cevapları dikkatle not aldı. (V) Yazıyı yayımlamadan önce konuğa doğrulatmayı kararlaştırdı.","Paragrafın düşünce akışını bozan cümle hangisidir?",["I","II","III","IV","V"],2,"medium","III. cümle spor haberlerinin sayfa dağılımını anlatıyor; diğerleri röportaj hazırlığı ve doğrulamasıyla ilgili."],
];

export const paragraphQuestions: ParagraphQuestion[] = [...make("main_idea", "ana-fikir", mainIdea), ...make("supporting_idea", "yardimci-dusunce", supporting), ...make("inference", "cikarim", inference), ...make("completion", "tamamlama", completion), ...make("flow", "akis", flow)];
export const PARAGRAPH_CATEGORIES = [
  { key: "main_idea" as const, title: "Ana Fikir", description: "Paragrafın vermek istediği temel düşünceyi bul." },
  { key: "supporting_idea" as const, title: "Yardımcı Düşünce", description: "Parçada yer alan veya yer almayan bilgileri ayırt et." },
  { key: "inference" as const, title: "Çıkarım Yapma", description: "Açıkça söylenmeyen ancak ulaşılabilen sonucu bul." },
  { key: "completion" as const, title: "Paragraf Tamamlama", description: "Paragrafın anlam ve anlatım bütünlüğünü tamamla." },
  { key: "flow" as const, title: "Akışı Bozan Cümle", description: "Paragrafın düşünce akışını bozan cümleyi belirle." },
  { key: "mixed" as const, title: "Karma Test", description: "Farklı paragraf soru türlerinden oluşan karışık çalışma." },
];
export function selectParagraphQuestions(category: ParagraphCategory | "mixed", count = 10, random = Math.random): ParagraphQuestion[] {
  if (category === "mixed") {
    const balanced = (["main_idea", "supporting_idea", "inference", "completion", "flow"] as ParagraphCategory[]).flatMap((item) => selectParagraphQuestions(item, Math.max(1, Math.floor(count / 5)), random));
    return balanced.sort(() => random() - 0.5).slice(0, count);
  }
  const pool = paragraphQuestions.filter((question) => question.category === category);
  const selected: ParagraphQuestion[] = [];
  while (pool.length && selected.length < count) selected.push(pool.splice(Math.floor(random() * pool.length), 1)[0]);
  return selected;
}
