export type AssignmentExerciseCategory =
  | "speed"
  | "attention"
  | "eye"
  | "memory"
  | "comprehension";

export type AssignmentExerciseDefinition = {
  slug: string;
  title: string;
  route: string;
  resultExerciseType: string;
  category: AssignmentExerciseCategory;
  assignmentEnabled: boolean;
  supportedSettings: string[];
};

export const ASSIGNMENT_EXERCISE_CATALOG: AssignmentExerciseDefinition[] = [
  {
    slug: "takistoskop",
    title: "Takistoskop",
    route: "/egzersizler/takistoskop",
    resultExerciseType: "tachistoscope",
    category: "speed",
    assignmentEnabled: true,
    supportedSettings: ["level", "speedMs", "durationMinutes", "targetCorrect", "contentType"],
  },
  {
    slug: "blok-okuma",
    title: "Blok Okuma",
    route: "/egzersizler/blok-okuma",
    resultExerciseType: "block-reading",
    category: "speed",
    assignmentEnabled: true,
    supportedSettings: ["wordsPerMinute", "durationMinutes", "groupSize", "textId"],
  },
  {
    slug: "gruplama-calismasi",
    title: "Gruplama Calismasi",
    route: "/egzersizler/gruplama-calismasi",
    resultExerciseType: "grouping-reading",
    category: "speed",
    assignmentEnabled: true,
    supportedSettings: ["wordsPerMinute", "durationMinutes", "groupSize", "textId"],
  },
  {
    slug: "golgeleme",
    title: "Golgeleme",
    route: "/egzersizler/golgeleme",
    resultExerciseType: "shadow-reading",
    category: "speed",
    assignmentEnabled: true,
    supportedSettings: ["wordsPerMinute", "durationMinutes", "textId"],
  },
  {
    slug: "odakli-okuma",
    title: "Odakli Okuma",
    route: "/egzersizler/odakli-okuma",
    resultExerciseType: "focused-reading",
    category: "speed",
    assignmentEnabled: true,
    supportedSettings: ["wordsPerMinute", "durationMinutes", "textId"],
  },
  {
    slug: "cift-tarafli-odak",
    title: "Cift Tarafli Odak",
    route: "/egzersizler/cift-tarafli-odak",
    resultExerciseType: "two-side-focus",
    category: "attention",
    assignmentEnabled: true,
    supportedSettings: ["level", "durationMinutes", "difficulty"],
  },
  {
    slug: "kare-gorme-alani",
    title: "Kare Gorme Alani",
    route: "/egzersizler/kare-gorme-alani",
    resultExerciseType: "square-vision",
    category: "attention",
    assignmentEnabled: true,
    supportedSettings: ["level", "durationMinutes", "difficulty"],
  },
  {
    slug: "harf-rakam-sayma",
    title: "Harf Rakam Sayma",
    route: "/egzersizler/harf-rakam-sayma",
    resultExerciseType: "letter-number-counting-focus",
    category: "attention",
    assignmentEnabled: true,
    supportedSettings: ["level", "durationMinutes", "difficulty"],
  },
  {
    slug: "ayni-olani-yakala",
    title: "Ayni Olani Yakala",
    route: "/egzersizler/ayni-olani-yakala",
    resultExerciseType: "catch-same",
    category: "attention",
    assignmentEnabled: true,
    supportedSettings: ["level", "durationMinutes", "difficulty"],
  },
  {
    slug: "dikkat-labirenti",
    title: "Dikkat Labirenti",
    route: "/egzersizler/dikkat-labirenti",
    resultExerciseType: "attention-maze",
    category: "attention",
    assignmentEnabled: true,
    supportedSettings: ["level", "durationMinutes", "difficulty"],
  },
  {
    slug: "benzer-kelimeler",
    title: "Benzer Kelimeler",
    route: "/egzersizler/benzer-kelimeler",
    resultExerciseType: "similar-words",
    category: "attention",
    assignmentEnabled: true,
    supportedSettings: ["level", "durationMinutes", "difficulty"],
  },
  {
    slug: "goz-kaslari",
    title: "Goz Kaslari",
    route: "/egzersizler/goz-kaslari",
    resultExerciseType: "eye-muscle",
    category: "eye",
    assignmentEnabled: true,
    supportedSettings: ["level", "durationMinutes"],
  },
  {
    slug: "goz-calismasi",
    title: "Goz Calismasi",
    route: "/egzersizler/goz-calismasi",
    resultExerciseType: "eye-muscle",
    category: "eye",
    assignmentEnabled: true,
    supportedSettings: ["level", "durationMinutes"],
  },
  {
    slug: "goz-beyin",
    title: "Goz Beyin",
    route: "/egzersizler/goz-beyin",
    resultExerciseType: "eye-brain",
    category: "eye",
    assignmentEnabled: true,
    supportedSettings: ["speedMs", "durationMinutes"],
  },
  {
    slug: "goz-egzersizleri-kolonlar",
    title: "Goz Egzersizleri Kolonlar",
    route: "/egzersizler/goz-egzersizleri-kolonlar",
    resultExerciseType: "eye-columns",
    category: "eye",
    assignmentEnabled: true,
    supportedSettings: ["speedMs", "durationMinutes"],
  },
  {
    slug: "kelime-tahmin",
    title: "Kelime Tahmin",
    route: "/egzersizler/kelime-tahmin",
    resultExerciseType: "word-guess",
    category: "memory",
    assignmentEnabled: true,
    supportedSettings: ["wordLength", "targetCorrect"],
  },
  {
    slug: "kelime-bulma",
    title: "Kelime Bulma",
    route: "/egzersizler/kelime-bulma",
    resultExerciseType: "word-finding",
    category: "memory",
    assignmentEnabled: true,
    supportedSettings: ["durationMinutes", "targetCorrect", "textId"],
  },
  {
    slug: "hafiza-gelistirme",
    title: "Hafıza Geliştirme",
    route: "/egzersizler/hafiza-gelistirme",
    resultExerciseType: "memory-game",
    category: "memory",
    assignmentEnabled: true,
    supportedSettings: ["level", "gridLayout", "displayMs", "fontSize"],
  },
  {
    slug: "kart-hafiza",
    title: "Kart Hafiza",
    route: "/egzersizler/kart-hafiza",
    resultExerciseType: "memory-game",
    category: "memory",
    assignmentEnabled: true,
    supportedSettings: ["level", "durationMinutes", "targetCorrect"],
  },
  {
    slug: "kart-eslestirme",
    title: "Kart Eslestirme",
    route: "/egzersizler/kart-eslestirme",
    resultExerciseType: "card-matching",
    category: "memory",
    assignmentEnabled: true,
    supportedSettings: ["level", "durationMinutes", "targetCorrect"],
  },
  {
    slug: "parcali-resim-kelime",
    title: "Parcali Resim Kelime",
    route: "/egzersizler/parcali-resim-kelime",
    resultExerciseType: "memory-game",
    category: "memory",
    assignmentEnabled: true,
    supportedSettings: ["level", "durationMinutes", "targetCorrect"],
  },
  {
    slug: "adam-asmaca",
    title: "Adam Asmaca",
    route: "/egzersizler/adam-asmaca",
    resultExerciseType: "hangman",
    category: "memory",
    assignmentEnabled: true,
    supportedSettings: ["wordLength", "targetCorrect"],
  },
  {
    slug: "gorsel-puzzle",
    title: "Gorsel Puzzle",
    route: "/egzersizler/gorsel-puzzle",
    resultExerciseType: "visual-puzzle",
    category: "memory",
    assignmentEnabled: true,
    supportedSettings: ["level", "durationMinutes", "targetCorrect"],
  },
  {
    slug: "anlama-testi",
    title: "Anlama Testi",
    route: "/egzersizler/anlama-testi",
    resultExerciseType: "reading-comprehension",
    category: "comprehension",
    assignmentEnabled: true,
        supportedSettings: ["textId", "targetSuccessRate", "questionCount"],
  },
  {
    slug: "okuma-hizi-testi",
    title: "Okuma Hızı Testi",
    route: "/egzersizler/okuma-hizi-testi",
    resultExerciseType: "reading-speed-test",
    category: "speed",
    assignmentEnabled: true,
    supportedSettings: ["textId", "fontSize"],
  },
  {
    slug: "renk-uyumu",
    title: "Renk Uyumu",
    route: "/egzersizler/renk-uyumu",
    resultExerciseType: "color-match",
    category: "attention",
    assignmentEnabled: true,
    supportedSettings: ["level", "durationMinutes", "targetCorrect"],
  },
];

export const ASSIGNMENT_EXERCISE_BY_SLUG = new Map(
  ASSIGNMENT_EXERCISE_CATALOG.map((item) => [item.slug, item]),
);
