import type { TwoSideFocusWordSet } from "./twoSideFocusShared";

export const TWO_SIDE_FOCUS_WORD_SETS: readonly TwoSideFocusWordSet[] = [
  { base: "kalem", variants: ["kelam", "kalen", "kalım"] },
  { base: "kitap", variants: ["katip", "kıtap", "kitapç"] },
  { base: "masa", variants: ["masal", "musa", "maşa"] },
  { base: "deniz", variants: ["denir", "beniz", "deniş"] },
  { base: "çiçek", variants: ["çilek", "çiçem", "çicek"] },
  { base: "sahil", variants: ["sahip", "sakin", "sahir"] },
  { base: "orman", variants: ["organ", "ortam", "orhan"] },
  { base: "güneş", variants: ["güreş", "gümüş", "günel"] },
  { base: "yıldız", variants: ["yalnız", "yıldır", "yıldızlı"] },
  { base: "ırmak", variants: ["ırgat", "irmik", "ırmaklı"] },
  { base: "bahçe", variants: ["bahane", "bahri", "bahçem"] },
  { base: "defter", variants: ["defne", "defterim", "defterci"] },
  { base: "renkli", variants: ["renkler", "renki", "renkçe"] },
  { base: "oyuncu", variants: ["oyunçu", "oyuncak", "oyunlu"] },
  { base: "sevgi", variants: ["sezgi", "sergi", "sevim"] },
  { base: "umutlu", variants: ["unuttu", "umuttu", "umutla"] },
  { base: "zaman", variants: ["saman", "zamanı", "zamans"] },
  { base: "şehir", variants: ["nehir", "sehir", "şehirli"] },
  { base: "köprü", variants: ["köpük", "kömür", "köprüm"] },
  { base: "rüzgar", variants: ["rüzgâr", "rüzgarı", "rüzgarlı"] },
  { base: "yağmur", variants: ["yamuk", "yağma", "yağmurlu"] },
  { base: "toprak", variants: ["yaprak", "toplam", "topraklı"] },
  { base: "dikkat", variants: ["dikat", "dikkât", "dikkatli"] },
  { base: "odaklı", variants: ["odakla", "ocaklı", "odakçı"] },
  { base: "hedef", variants: ["heves", "heder", "hedefli"] },
  { base: "başarı", variants: ["başka", "başari", "başarılı"] },
  { base: "anlama", variants: ["anlatma", "anlams", "anlayan"] },
  { base: "okuma", variants: ["okumu", "dokuma", "okuyan"] },
] as const satisfies readonly TwoSideFocusWordSet[];
