import type { Student } from "@/lib/students/types";

export const DEMO_STUDENT: Student = {
  id: "demo-student",
  name: "Demo Öğrenci",
  username: "ogrenci",
  password: "1234",
  className: "Demo",
  classLevel: "Demo",
  parentName: "",
  phone: "",
  parentPhone: "",
  status: "active",
  isActive: true,
  createdAt: "2026-07-05T00:00:00.000Z",
};

export const MOCK_STUDENTS: Student[] = [
  DEMO_STUDENT,
  {
    id: "std-ceren-bora",
    name: "Ceren Bora",
    username: "ceren.bora",
    password: "Ceren2026!",
    classLevel: "4-A",
    parentName: "Seda Bora",
    parentPhone: "05550000001",
    educationStatus: "speed-reading",
    status: "active",
    createdAt: "2026-01-10T09:00:00.000Z",
  },
  {
    id: "std-aras-alp-baglica",
    name: "Aras Alp Bağlıca",
    username: "aras.baglica",
    password: "Aras2026!",
    classLevel: "5-B",
    parentName: "Murat Bağlıca",
    educationStatus: "speed-reading",
    status: "active",
    createdAt: "2026-01-12T09:00:00.000Z",
  },
  {
    id: "std-yekta-angin",
    name: "Yekta Angın",
    username: "yekta.angin",
    password: "Yekta2026!",
    classLevel: "6-A",
    parentName: "Deniz Angın",
    educationStatus: "general",
    status: "active",
    createdAt: "2026-01-15T09:00:00.000Z",
  },
  {
    id: "std-mila-vatan",
    name: "Mila Vatan",
    username: "mila.vatan",
    password: "Mila2026!",
    classLevel: "3-C",
    parentName: "Ece Vatan",
    educationStatus: "general",
    status: "passive",
    createdAt: "2026-01-18T09:00:00.000Z",
  },
];
