export type HeceleGrade = 1 | 2;
export type HeceleSupportLevel = "very-slow" | "slow" | "word-by-word";
export type ReadingItemType = "word" | "sentence";

export type WordReadingItem = {
  id: string;
  grade: HeceleGrade;
  type: "word";
  text: string;
  syllables: string[];
};

export type SentenceToken = {
  text: string;
  normalized: string;
  syllables: string[];
};

export type SentenceReadingItem = {
  id: string;
  grade: HeceleGrade;
  type: "sentence";
  text: string;
  tokens: SentenceToken[];
};

export type HeceleReadingItem = WordReadingItem | SentenceReadingItem;

export type SupportConfig = {
  id: HeceleSupportLevel;
  label: string;
  shortLabel: string;
  description: string;
  syllableSupport: boolean;
  syllablePauseMs: number;
  wordPauseMs: number;
  modelRate: number;
};

export const HECELE_SUPPORT_LEVELS: readonly SupportConfig[] = [
  {
    id: "very-slow",
    label: "Çok Yavaş",
    shortLabel: "Çok Yavaş",
    description: "Heceleri gör, uzun aralarla dinle ve kelimeyi birlikte oluştur.",
    syllableSupport: true,
    syllablePauseMs: 700,
    wordPauseMs: 950,
    modelRate: 0.76,
  },
  {
    id: "slow",
    label: "Yavaş",
    shortLabel: "Yavaş",
    description: "Hece desteğini koru, daha kısa aralarla kelimeye ve cümleye ilerle.",
    syllableSupport: true,
    syllablePauseMs: 500,
    wordPauseMs: 700,
    modelRate: 0.86,
  },
  {
    id: "word-by-word",
    label: "Kelime Kelime",
    shortLabel: "Kelime Kelime",
    description: "Kelimeleri sırayla takip et; ihtiyaç olursa heceyi geçici olarak göster.",
    syllableSupport: false,
    syllablePauseMs: 0,
    wordPauseMs: 520,
    modelRate: 0.92,
  },
];

export const HECELE_GRADES: readonly HeceleGrade[] = [1, 2];
export const HECELE_TASK_COUNT = 8;

// The syllable map is intentionally explicit. It is not generated by a
// heuristic algorithm because Turkish syllable boundaries need verification.
const SYLLABLES: Record<string, string[]> = {
  ağaç: ["a", "ğaç"], akşam: ["ak", "şam"], alan: ["a", "lan"], alarm: ["a", "larm"],
  altın: ["al", "tın"], anne: ["an", "ne"], araba: ["a", "ra", "ba"], armut: ["ar", "mut"],
  arı: ["a", "rı"], arkadaş: ["ar", "ka", "daş"], ayakkabı: ["a", "yak", "ka", "bı"],
  ayçiçeği: ["ay", "çi", "çe", "ği"], ayva: ["ay", "va"], balık: ["ba", "lık"], balon: ["ba", "lon"],
  bardak: ["bar", "dak"], basketbol: ["bas", "ket", "bol"], bayrak: ["bay", "rak"], bebek: ["be", "bek"],
  bisiklet: ["bi", "sik", "let"], bulut: ["bu", "lut"], bütün: ["bü", "tün"], cadde: ["cad", "de"],
  cam: ["cam"], ceviz: ["ce", "viz"], çadır: ["ça", "dır"], çanta: ["çan", "ta"], çiçek: ["çi", "çek"],
  çilek: ["çi", "lek"], çocuk: ["ço", "cuk"], dağ: ["dağ"], dakika: ["da", "ki", "ka"], deniz: ["de", "niz"],
  ders: ["ders"], dondurma: ["don", "dur", "ma"], dosya: ["dos", "ya"], dünya: ["dün", "ya"],
  ekmek: ["ek", "mek"], elbise: ["el", "bi", "se"], elma: ["el", "ma"], erik: ["e", "rik"], ev: ["ev"],
  fener: ["fe", "ner"], fırça: ["fır", "ça"], fil: ["fil"], fotoğraf: ["fo", "to", "ğraf"], gökkuşağı: ["gök", "ku", "şa", "ğı"],
  göl: ["göl"], gözlük: ["göz", "lük"], güneş: ["gü", "neş"], hafta: ["haf", "ta"], haber: ["ha", "ber"],
  halı: ["ha", "lı"], harita: ["ha", "ri", "ta"], havuç: ["ha", "vuç"], heyecan: ["he", "ye", "can"],
  horoz: ["ho", "roz"], ıhlamur: ["ıh", "la", "mur"], ışık: ["ı", "şık"], ırmak: ["ır", "mak"],
  incir: ["in", "cir"], ip: ["ip"], kitap: ["ki", "tap"], kedi: ["ke", "di"], kelebek: ["ke", "le", "bek"],
  keman: ["ke", "man"], kepçe: ["kep", "çe"], kiraz: ["ki", "raz"], kolye: ["kol", "ye"], komşu: ["kom", "şu"],
  köpek: ["kö", "pek"], kova: ["ko", "va"], kurabiye: ["ku", "ra", "bi", "ye"], kuş: ["kuş"],
  lamba: ["lam", "ba"], limon: ["li", "mon"], mandalina: ["man", "da", "li", "na"], masa: ["ma", "sa"],
  mektup: ["mek", "tup"], merdiven: ["mer", "di", "ven"], meyve: ["mey", "ve"], mum: ["mum"], müzik: ["mü", "zik"],
  oyuncak: ["o", "yun", "cak"], okul: ["o", "kul"], orman: ["or", "man"], otobüs: ["o", "to", "büs"],
  ördek: ["ör", "dek"], öğretmen: ["öğ", "ret", "men"], papatya: ["pa", "pat", "ya"], patates: ["pa", "ta", "tes"],
  pencere: ["pen", "ce", "re"], perde: ["per", "de"], perşembe: ["per", "şem", "be"], pilot: ["pi", "lot"],
  portakal: ["por", "ta", "kal"], radyo: ["rad", "yo"], renkli: ["renk", "li"], resim: ["re", "sim"], robot: ["ro", "bot"],
  salata: ["sa", "la", "ta"], sandalye: ["san", "dal", "ye"], sarı: ["sa", "rı"], sebze: ["seb", "ze"],
  sepet: ["se", "pet"], serçe: ["ser", "çe"], simit: ["si", "mit"], silgi: ["sil", "gi"], sinema: ["si", "ne", "ma"],
  sokak: ["so", "kak"], soru: ["so", "ru"], süpürge: ["sü", "pür", "ge"], şapka: ["şap", "ka"], şeker: ["şe", "ker"],
  şemsiye: ["şem", "si", "ye"], tabak: ["ta", "bak"], tavşan: ["tav", "şan"], telefon: ["te", "le", "fon"],
  terlik: ["ter", "lik"], tiyatro: ["ti", "yat", "ro"], top: ["top"], topa: ["to", "pa"], topu: ["to", "pu"],
  traktör: ["trak", "tör"], uçak: ["u", "çak"], uçurtma: ["u", "çurt", "ma"], yağmur: ["yağ", "mur"],
  yazı: ["ya", "zı"], yoğurt: ["yo", "ğurt"], yıldız: ["yıl", "dız"], yüzme: ["yüz", "me"],
  zürafa: ["zü", "ra", "fa"], akıllı: ["a", "kıl", "lı"], balkon: ["bal", "kon"], bilgisayar: ["bil", "gi", "sa", "yar"],
  cumartesi: ["cu", "mar", "te", "si"], cümle: ["cüm", "le"], dikkatli: ["dik", "kat", "li"],
  dondurucu: ["don", "du", "ru", "cu"], eğlence: ["eğ", "len", "ce"], enstrüman: ["ens", "trü", "man"],
  fidan: ["fi", "dan"], gökyüzü: ["gök", "yü", "zü"], güzel: ["gü", "zel"], günlük: ["gün", "lük"],
  hazırlık: ["ha", "zır", "lık"], hikâye: ["hi", "kâ", "ye"], istasyon: ["is", "tas", "yon"],
  kabarcık: ["ka", "bar", "cık"], kahvaltı: ["kah", "val", "tı"], kalabalık: ["ka", "la", "ba", "lık"],
  karınca: ["ka", "rın", "ca"], karpuz: ["kar", "puz"], kırlangıç: ["kır", "lan", "gıç"],
  kitaplık: ["ki", "tap", "lık"], kırtasiye: ["kır", "ta", "si", "ye"], köprü: ["köp", "rü"],
  marangoz: ["ma", "ran", "goz"], masal: ["ma", "sal"], matematik: ["ma", "te", "ma", "tik"],
  mutluluk: ["mut", "lu", "luk"], oyuncular: ["o", "yun", "cu", "lar"], özgürlük: ["öz", "gür", "lük"],
  piknik: ["pik", "nik"], planlı: ["plan", "lı"], problem: ["prob", "lem"], sağlık: ["sağ", "lık"],
  sabah: ["sa", "bah"], saklambaç: ["sak", "lam", "baç"], sıcak: ["sı", "cak"], sınıf: ["sı", "nıf"],
  sporcu: ["spor", "cu"], sürpriz: ["sür", "priz"], temiz: ["te", "miz"],
  toplantı: ["top", "lan", "tı"], turuncu: ["tu", "run", "cu"], uzun: ["u", "zun"], üzümlü: ["ü", "züm", "lü"],
  uğur: ["u", "ğur"], yarışma: ["ya", "rış", "ma"], yardım: ["yar", "dım"], yemek: ["ye", "mek"],
  yelkenli: ["yel", "ken", "li"], yeniden: ["ye", "ni", "den"], zengin: ["zen", "gin"], zeytin: ["zey", "tin"],
  açtı: ["aç", "tı"], aldı: ["al", "dı"], başladı: ["baş", "la", "dı"], baktı: ["bak", "tı"],
  bekledi: ["bek", "le", "di"], bildi: ["bil", "di"], buldu: ["bul", "du"], çıktı: ["çık", "tı"],
  çaldı: ["çal", "dı"], çizdi: ["çiz", "di"], dinledi: ["din", "le", "di"], dokundu: ["do", "kun", "du"],
  döndü: ["dön", "dü"], gördü: ["gör", "dü"], gülümsedi: ["gü", "lüm", "se", "di"], içti: ["iç", "ti"],
  izledi: ["iz", "le", "di"], koştu: ["koş", "tu"], konuştu: ["ko", "nuş", "tu"], koydu: ["koy", "du"],
  okudu: ["o", "ku", "du"], oynadı: ["oy", "na", "dı"], ördü: ["ör", "dü"], paylaştı: ["pay", "laş", "tı"],
  seçti: ["seç", "ti"], söyledi: ["söy", "le", "di"], taşıdı: ["ta", "şı", "dı"], topladı: ["top", "la", "dı"],
  tuttu: ["tut", "tu"], uyudu: ["u", "yu", "du"], verdi: ["ver", "di"], yaptı: ["yap", "tı"],
  yazdı: ["yaz", "dı"], yedi: ["ye", "di"], geldi: ["gel", "di"], gitti: ["git", "ti"],
  bizim: ["bi", "zim"], benim: ["be", "nim"], onun: ["o", "nun"], bugün: ["bu", "gün"],
  burada: ["bu", "ra", "da"], birlikte: ["bir", "lik", "te"], sonra: ["son", "ra"], şimdi: ["şim", "di"],
  çok: ["çok"], küçük: ["kü", "çük"], büyük: ["bü", "yük"], hızlı: ["hız", "lı"], yavaş: ["ya", "vaş"],
  yeni: ["ye", "ni"], eski: ["es", "ki"], mavi: ["ma", "vi"], yeşil: ["ye", "şil"], kırmızı: ["kır", "mı", "zı"],
  mor: ["mor"], pembe: ["pem", "be"], sessiz: ["ses", "siz"],
  mutlu: ["mut", "lu"], hazır: ["ha", "zır"], herkes: ["her", "kes"],
  neden: ["ne", "den"], nasıl: ["na", "sıl"], hangi: ["han", "gi"],
  ali: ["a", "li"], ece: ["e", "ce"], can: ["can"], duru: ["du", "ru"], süt: ["süt"],
  baba: ["ba", "ba"], kalem: ["ka", "lem"], ve: ["ve"], kaldı: ["kal", "dı"], ekmeği: ["ek", "me", "ği"], yuvasına: ["yu", "va", "sı", "na"], yarışmada: ["ya", "rış", "ma", "da"], dondurucuya: ["don", "du", "ru", "cu", "ya"],
  eve: ["e", "ve"], sildi: ["sil", "di"], uçtu: ["uç", "tu"],
  dala: ["da", "la"], kondu: ["kon", "du"], kapıya: ["ka", "pı", "ya"], çantayı: ["çan", "ta", "yı"],
  vurdu: ["vur", "du"], gökte: ["gök", "te"], durdu: ["dur", "du"], cama: ["ca", "ma"],
  halıda: ["ha", "lı", "da"], çay: ["çay"], sessizce: ["ses", "siz", "ce"],
  su: ["su"], bisiklete: ["bi", "sik", "le", "te"], bindi: ["bin", "di"], oldu: ["ol", "du"],
  yerde: ["yer", "de"], kapıyı: ["ka", "pı", "yı"], sandalyede: ["san", "dal", "ye", "de"],
  arkadaşım: ["ar", "ka", "da", "şım"], sürdü: ["sür", "dü"], bir: ["bir"], çiçeğin: ["çi", "çe", "ğin"],
  üstüne: ["üs", "tü", "ne"], sepetin: ["se", "pe", "tin"], içinde: ["i", "çin", "de"], çocuklar: ["ço", "cuk", "lar"],
  bahçede: ["bah", "çe", "de"], yağmurdan: ["yağ", "mur", "dan"], kırtasiyeden: ["kır", "ta", "si", "ye", "den"],
  aldık: ["al", "dık"], kahvaltıda: ["kah", "val", "tı", "da"], yedik: ["ye", "dik"], merdivenin: ["mer", "di", "ve", "nin"],
  yanında: ["ya", "nın", "da"], saksı: ["sak", "sı"], var: ["var"], masanın: ["ma", "sa", "nın"], üzerinde: ["ü", "ze", "rin", "de"],
  şemsiyeni: ["şem", "si", "ye", "ni"], al: ["al"], dışarıda: ["dı", "şa", "rı", "da"], dersi: ["der", "si"], eğlenceli: ["eğ", "len", "ce", "li"],
  gökyüzünde: ["gök", "yü", "zün", "de"], hızlıca: ["hız", "lı", "ca"], tiyatroda: ["ti", "yat", "ro", "da"], komik: ["ko", "mik"],
  oyun: ["o", "yun"], izledik: ["iz", "le", "dik"], çalışıyor: ["ça", "lı", "şı", "yor"], güneşe: ["gü", "ne", "şe"], doğru: ["doğ", "ru"],
  piknikte: ["pik", "nik", "te"], taze: ["ta", "ze"], meyveler: ["mey", "ve", "ler"], paylaştık: ["pay", "laş", "tık"], öğrenci: ["öğ", "ren", "ci"],
  soruyu: ["so", "ru", "yu"], günü: ["gü", "nü"], sinemaya: ["si", "ne", "ma", "ya"], gidebilir: ["gi", "de", "bi", "lir"], miyiz: ["mi", "yiz"],
  çorba: ["çor", "ba"], herkesin: ["her", "ke", "sin"], içini: ["i", "çi", "ni"], ısıttı: ["ı", "sıt", "tı"], denizde: ["de", "niz", "de"],
  ilerledi: ["i", "ler", "le", "di"], çantamı: ["çan", "ta", "mı"], akşamdan: ["ak", "şam", "dan"], düzenledim: ["dü", "zen", "le", "dim"],
  çalıştı: ["ça", "lış", "tı"], hakkında: ["hak", "kın", "da"], kısa: ["kı", "sa"], koyduk: ["koy", "duk"], istasyonda: ["is", "tas", "yon", "da"],
  tren: ["tren"], hediye: ["he", "di", "ye"], altında: ["al", "tın", "da"], saklıydı: ["sak", "lıy", "dı"],
  istedi: ["is", "te", "di"],
};

const GRADE_1_WORDS: WordReadingItem[] = [
  ["masa", "ma-sa"], ["kalem", "ka-lem"], ["kitap", "ki-tap"], ["balon", "ba-lon"], ["kedi", "ke-di"],
  ["köpek", "kö-pek"], ["elma", "el-ma"], ["armut", "ar-mut"], ["araba", "a-ra-ba"], ["okul", "o-kul"],
  ["anne", "an-ne"], ["baba", "ba-ba"], ["bebek", "be-bek"], ["çanta", "çan-ta"], ["kapı", "ka-pı"],
  ["pencere", "pen-ce-re"], ["sandalye", "san-dal-ye"], ["balık", "ba-lık"], ["çiçek", "çi-çek"], ["çilek", "çi-lek"],
  ["bulut", "bu-lut"], ["güneş", "gü-neş"], ["yağmur", "yağ-mur"], ["uçak", "u-çak"], ["göl", "göl"],
  ["kuş", "kuş"], ["top", "top"], ["oyuncak", "o-yun-cak"], ["fırça", "fır-ça"], ["silgi", "sil-gi"],
  ["tabak", "ta-bak"], ["bardak", "bar-dak"], ["lamba", "lam-ba"], ["kova", "ko-va"], ["limon", "li-mon"],
  ["kiraz", "ki-raz"], ["simit", "si-mit"], ["şapka", "şap-ka"], ["terlik", "ter-lik"], ["papatya", "pa-pat-ya"],
].map(([text, syllableText], index) => ({ id: `g1-word-${index + 1}`, grade: 1, type: "word", text, syllables: syllableText.split("-") }));

const GRADE_2_WORDS: WordReadingItem[] = [
  ["arkadaş", "ar-ka-daş"], ["ayakkabı", "a-yak-ka-bı"], ["bisiklet", "bi-sik-let"], ["kelebek", "ke-le-bek"], ["kurabiye", "ku-ra-bi-ye"],
  ["mandalina", "man-da-li-na"], ["merdiven", "mer-di-ven"], ["öğretmen", "öğ-ret-men"], ["şemsiye", "şem-si-ye"], ["telefon", "te-le-fon"],
  ["dondurma", "don-dur-ma"], ["süpürge", "sü-pür-ge"], ["gökyüzü", "gök-yü-zü"], ["gökkuşağı", "gök-ku-şa-ğı"], ["ıhlamur", "ıh-la-mur"],
  ["bilgisayar", "bil-gi-sa-yar"], ["kırtasiye", "kır-ta-si-ye"], ["matematik", "ma-te-ma-tik"], ["kalabalık", "ka-la-ba-lık"], ["hazırlık", "ha-zır-lık"],
  ["kahvaltı", "kah-val-tı"], ["saklambaç", "sak-lam-baç"], ["kırlangıç", "kır-lan-gıç"], ["karınca", "ka-rın-ca"], ["marangoz", "ma-ran-goz"],
  ["enstrüman", "ens-trü-man"], ["istasyon", "is-tas-yon"], ["dondurucu", "don-du-ru-cu"], ["oyuncular", "o-yun-cu-lar"], ["kitaplık", "ki-tap-lık"],
  ["özgürlük", "öz-gür-lük"], ["mutluluk", "mut-lu-luk"], ["toplantı", "top-lan-tı"], ["yarışma", "ya-rış-ma"], ["yelkenli", "yel-ken-li"],
  ["ayçiçeği", "ay-çi-çe-ği"], ["portakal", "por-ta-kal"], ["fotoğraf", "fo-to-ğraf"], ["tiyatro", "ti-yat-ro"], ["zengin", "zen-gin"],
].map(([text, syllableText], index) => ({ id: `g2-word-${index + 1}`, grade: 2, type: "word", text, syllables: syllableText.split("-") }));

function normalizeToken(token: string): string {
  return token
    .toLocaleLowerCase("tr-TR")
    .replace(/^[^\p{L}İıÇçĞğÖöŞşÜü]+|[^\p{L}İıÇçĞğÖöŞşÜü]+$/gu, "");
}

function makeSentence(id: string, grade: HeceleGrade, text: string): SentenceReadingItem {
  const tokens = text.split(/\s+/).map((token) => {
    const normalized = normalizeToken(token);
    const syllables = SYLLABLES[normalized];
    if (!syllables) throw new Error(`Eksik doğrulanmış hece verisi: ${normalized}`);
    return { text: token, normalized, syllables: [...syllables] };
  });
  return { id, grade, type: "sentence", text, tokens };
}

const GRADE_1_SENTENCE_TEXTS = [
  "Ali topu aldı.", "Ece kitap okudu.", "Kedi süt içti.", "Baba eve geldi.", "Anne masa sildi.",
  "Mavi balon uçtu.", "Kuş dala kondu.", "Bebek uyudu.", "Can elma yedi.", "Duru kalem seçti.",
  "Köpek kapıya baktı.", "Ece çantayı aldı.", "Ali topa vurdu.", "Güneş çok sıcak.", "Bulut gökte durdu.",
  "Yağmur cama vurdu.", "Kedi halıda uyudu.", "Baba kitap okudu.", "Anne çay içti.", "Çocuk sessizce dinledi.",
  "Kuş su içti.", "Ece çiçek topladı.", "Ali bisiklete bindi.", "Bebek gülümsedi.", "Masa temiz oldu.",
  "Sarı kalem yerde.", "Küçük kedi koştu.", "Baba kapıyı açtı.", "Anne meyve aldı.", "Çanta sandalyede durdu.",
];

const GRADE_2_SENTENCE_TEXTS = [
  "Arkadaşım bisiklet sürdü.", "Öğretmen güzel bir masal okudu.", "Kelebek çiçeğin üstüne kondu.", "Mandalina sepetin içinde durdu.",
  "Çocuklar bahçede saklambaç oynadı.", "Gökkuşağı yağmurdan sonra çıktı.", "Kırtasiyeden renkli kalem aldık.", "Kahvaltıda yoğurt ve zeytin yedik.",
  "Merdivenin yanında büyük bir saksı var.", "Telefon masanın üzerinde kaldı.", "Şemsiyeni al, dışarıda yağmur var!", "Bugün matematik dersi çok eğlenceli.",
  "Kırlangıç gökyüzünde hızlıca uçtu.", "Marangoz yeni bir kitaplık yaptı.", "Tiyatroda komik bir oyun izledik.", "Bilgisayar sessizce çalışıyor.",
  "Ayçiçeği güneşe doğru döndü.", "Piknikte taze meyveler paylaştık.", "Küçük karınca ekmeği yuvasına taşıdı.", "Dikkatli öğrenci soruyu yeniden okudu.",
  "Cumartesi günü sinemaya gidebilir miyiz?", "Sıcak çorba herkesin içini ısıttı.", "Yelkenli mavi denizde ilerledi.", "Hazırlık çantamı akşamdan düzenledim.",
  "Oyuncular yarışmada birlikte çalıştı.", "Özgürlük hakkında kısa bir hikâye yazdı.", "Dondurucuya üzümlü dondurma koyduk.", "İstasyonda uzun bir tren bekledi.",
  "Sürpriz hediye masanın altında saklıydı.", "Herkes temiz ve planlı bir sınıf istedi.",
];

export const HECELE_GRADE_1_WORDS = GRADE_1_WORDS;
export const HECELE_GRADE_2_WORDS = GRADE_2_WORDS;
export const HECELE_GRADE_1_SENTENCES = GRADE_1_SENTENCE_TEXTS.map((text, index) => makeSentence(`g1-sentence-${index + 1}`, 1, text));
export const HECELE_GRADE_2_SENTENCES = GRADE_2_SENTENCE_TEXTS.map((text, index) => makeSentence(`g2-sentence-${index + 1}`, 2, text));

export const HECELE_CONTENT: Record<HeceleGrade, { words: WordReadingItem[]; sentences: SentenceReadingItem[] }> = {
  1: { words: HECELE_GRADE_1_WORDS, sentences: HECELE_GRADE_1_SENTENCES },
  2: { words: HECELE_GRADE_2_WORDS, sentences: HECELE_GRADE_2_SENTENCES },
};

function rotate<T>(items: readonly T[], offset: number): T[] {
  if (items.length === 0) return [];
  const safeOffset = ((offset % items.length) + items.length) % items.length;
  return [...items.slice(safeOffset), ...items.slice(0, safeOffset)];
}

export function getSupportConfig(level: HeceleSupportLevel): SupportConfig {
  return HECELE_SUPPORT_LEVELS.find((config) => config.id === level) ?? HECELE_SUPPORT_LEVELS[0];
}

export function createHeceleSession(
  grade: HeceleGrade,
  supportLevel: HeceleSupportLevel,
  previousSessionIds: readonly string[] = [],
): HeceleReadingItem[] {
  const content = HECELE_CONTENT[grade];
  const offset = previousSessionIds.length === 0 ? 0 : previousSessionIds.reduce((sum, id) => sum + id.length, 0);
  const wordCount = supportLevel === "very-slow" ? 4 : supportLevel === "slow" ? 5 : 7;
  const words = [...content.words].sort((a, b) => a.syllables.length - b.syllables.length || a.text.length - b.text.length);
  const sentences = [...content.sentences].sort((a, b) => a.tokens.length - b.tokens.length || a.text.length - b.text.length);
  const selectedWords = rotate(words, offset).slice(0, 4);
  const selectedSentences = rotate(sentences, offset + wordCount).slice(0, 4);
  return [...selectedWords, ...selectedSentences];
}

export function validateHeceleContent(): string[] {
  const errors: string[] = [];
  const allItems = [...HECELE_GRADE_1_WORDS, ...HECELE_GRADE_2_WORDS, ...HECELE_GRADE_1_SENTENCES, ...HECELE_GRADE_2_SENTENCES];
  const ids = new Set<string>();
  const texts = new Set<string>();
  for (const item of allItems) {
    if (ids.has(item.id)) errors.push(`Tekrarlanan kimlik: ${item.id}`);
    ids.add(item.id);
    if (texts.has(item.text)) errors.push(`Tekrarlanan içerik: ${item.text}`);
    texts.add(item.text);
    if (!item.text.trim()) errors.push(`Boş içerik: ${item.id}`);
    if (item.type === "word" && item.syllables.join("") !== item.text) errors.push(`Hece birleştirme hatası: ${item.id}`);
    if (item.type === "sentence") {
      for (const token of item.tokens) {
        if (token.syllables.join("") !== token.normalized) errors.push(`Cümle hece hatası: ${item.id}/${token.normalized}`);
      }
    }
  }
  if (HECELE_GRADE_1_WORDS.length < 40) errors.push("1. sınıf kelime sayısı 40'tan az");
  if (HECELE_GRADE_1_SENTENCES.length < 30) errors.push("1. sınıf cümle sayısı 30'dan az");
  if (HECELE_GRADE_2_WORDS.length < 40) errors.push("2. sınıf kelime sayısı 40'tan az");
  if (HECELE_GRADE_2_SENTENCES.length < 30) errors.push("2. sınıf cümle sayısı 30'dan az");
  return errors;
}

export const HECELE_CONTENT_VALIDATION_ERRORS = validateHeceleContent();
