create table if not exists public.paragraph_questions (
  id text primary key,
  category text not null,
  difficulty text not null,
  grade_band text not null,
  passage text not null,
  question text not null,
  options jsonb not null,
  correct_index smallint not null,
  explanation text not null,
  is_active boolean not null default false,
  source text not null default 'manual',
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text,
  constraint paragraph_questions_category_check check (category in ('main_idea', 'supporting_idea', 'inference', 'completion', 'flow')),
  constraint paragraph_questions_difficulty_check check (difficulty in ('easy', 'medium', 'hard')),
  constraint paragraph_questions_grade_band_check check (grade_band in ('4-5', '6-7', '8', 'high-school')),
  constraint paragraph_questions_options_array_check check (jsonb_typeof(options) = 'array' and jsonb_array_length(options) = 5),
  constraint paragraph_questions_correct_index_check check (correct_index between 0 and 4),
  constraint paragraph_questions_source_check check (source in ('migration', 'manual', 'ai'))
);

alter table public.paragraph_questions enable row level security;
alter table public.paragraph_questions force row level security;

revoke all on table public.paragraph_questions from anon, authenticated;
grant select on table public.paragraph_questions to service_role;

drop policy if exists paragraph_questions_service_role_select on public.paragraph_questions;
create policy paragraph_questions_service_role_select
  on public.paragraph_questions
  for select
  to service_role
  using (true);

create index if not exists paragraph_questions_active_filter_idx
  on public.paragraph_questions (category, difficulty, grade_band)
  where is_active = true and archived_at is null;

insert into public.paragraph_questions (
  id, category, difficulty, grade_band, passage, question, options, correct_index, explanation,
  is_active, source, archived_at
) values
  ('ana-fikir-01', 'main_idea', 'easy', '6-7', 'Bir kitabı bitirdiğimizde yalnızca olayları öğrenmiş olmayız. Farklı kişilerin kararlarını düşünür, kendi hayatımızla karşılaştırmalar yaparız. Bu yüzden düzenli okuma, kelime bilgisinin yanında yorumlama becerisini de geliştirir.', 'Bu paragrafın ana düşüncesi nedir? Metindeki temel ilişkiye göre yanıtlayınız.', '["Düzenli okuma, farklı zihinsel becerileri birlikte geliştirir.","Her kitap gerçek bir olay anlatır.","Okurlar yalnızca kelime öğrenir.","Kitap kahramanları doğru karar verir.","Okuma süresi bütün öğrenciler için aynıdır."]'::jsonb, 0, 'Paragraf hem kelime bilgisini hem de yorumlamayı birlikte vurguluyor; doğru cevap iki sonucu kapsıyor.', true, 'migration', null),
  ('ana-fikir-02', 'main_idea', 'easy', '6-7', 'Okul bahçesine dikilen ağaçlar birkaç yıl içinde gölge vermeye başladı. Öğrenciler teneffüslerde bu alanlarda dinlenirken bahçedeki kuşları ve böcekleri de gözlemledi. Küçük bir düzenleme, okulun kullanımını ve canlı çeşitliliğini değiştirdi.', 'Parçanın temel düşüncesi hangisidir? Parçanın verdiği bilgilere göre düşününüz.', '["Ağaçlar yalnızca gölge sağlar.","Yeşil alanlar okul yaşamını ve çevredeki canlıları olumlu etkiler.","Öğrenciler teneffüste gözlem yapamaz.","Böcekler okul bahçelerine zarar verir.","Ağaçların büyümesi birkaç gün sürer."]'::jsonb, 1, 'İkinci seçenek gölge, dinlenme ve canlı gözlemi sonuçlarını birlikte açıklayarak parçanın tamamını kapsar.', true, 'migration', null),
  ('ana-fikir-03', 'main_idea', 'easy', '6-7', 'Bir hedef belirlemek, ne yapacağımızı bilmemizi sağlar; fakat hedefe ulaşmak için yöntemi de planlamak gerekir. Örneğin sınava hazırlanan bir öğrenci konuları günlere böler ve ilerlemesini düzenli aralıklarla kontrol eder.', 'Yazarın asıl vurgusu nedir? Doğru seçeneği metnin bütünüyle karşılaştırınız.', '["Her sınav aynı yöntemle kazanılır.","Hedefler yalnızca yazılı olarak tutulmalıdır.","Başarı için hedefi uygulanabilir bir planla desteklemek gerekir.","Konular son gün çalışılmalıdır.","İlerleme kontrolü zaman kaybıdır."]'::jsonb, 2, 'Metin hedef koymayı tek başına yeterli görmüyor; hedefin plan ve kontrolle desteklenmesini savunuyor.', true, 'migration', null),
  ('ana-fikir-04', 'main_idea', 'medium', '6-7', 'Kentlerde bisiklet yollarının artması, kısa mesafelerde otomobil kullanımını azaltabilir. İnsanlar daha fazla hareket ederken sokaklardaki gürültü ve hava kirliliği de azalır. Böylece ulaşım tercihi, şehirdeki yaşam kalitesini etkiler.', 'Bu parçanın ana fikri nedir? Anlatılan durumun sonucunu dikkate alınız.', '["Bisiklet yalnızca sporcular içindir.","Otomobiller bütün şehirlerde yasaklanmalıdır.","Bisiklet yolları yalnızca trafiği düzenler.","Bisiklet ulaşımı, şehir yaşamına çevresel ve sağlık açısından katkı sağlar.","Hava kirliliğinin tek nedeni ulaşımdır."]'::jsonb, 3, 'D seçeneği ulaşımın hareket, gürültü, hava ve yaşam kalitesi üzerindeki birlikte etkisini özetler.', true, 'migration', null),
  ('ana-fikir-05', 'main_idea', 'medium', '6-7', 'Bir müzik eserini dinlerken yalnızca melodiyi değil, kullanılan çalgıların birbirine nasıl eşlik ettiğini de fark edebiliriz. Dikkatli dinleme, eserin neden hüzünlü, neşeli ya da hareketli hissettirdiğini anlamayı kolaylaştırır.', 'Paragrafın ana düşüncesi hangisidir? Metindeki ayrıntıları birlikte değerlendiriniz.', '["Her müzik eseri aynı duyguyu verir.","Çalgıların sayısı eserin değerini belirler.","Melodi müzikte önemsizdir.","Hüzünlü eserler daha iyi çalınır.","Dikkatli dinlemek, müziğin yapısını ve duygusunu anlamayı sağlar."]'::jsonb, 4, 'Parça, melodinin ötesindeki eşlikleri fark etmenin eserin duygusunu anlamaya yardım ettiğini anlatıyor.', true, 'migration', null),
  ('ana-fikir-06', 'main_idea', 'medium', '6-7', 'Bir mahalledeki paylaşım dolabı, kullanılmayan eşyaların çöpe gitmesini önlemek için kurulmuştu. İhtiyacı olmayanlar temiz eşyalarını bırakıyor, ihtiyacı olanlar da bunları ücretsiz alıyordu. Zamanla dolap, komşular arasında güven ve dayanışma oluşturdu.', 'Bu paragrafta anlatılmak istenen nedir? Yazarın vurgusunu göz önünde bulundurunuz.', '["Paylaşım uygulamaları hem israfı azaltır hem de dayanışmayı güçlendirir.","Eşyalar yalnızca satın alınmalıdır.","Komşular birbirinden eşya almamalıdır.","Dolapların bakımı imkânsızdır.","İsraf yalnızca evlerde görülür."]'::jsonb, 0, 'İkinci seçenek hem israfın azalmasını hem de komşuluk dayanışmasını birlikte karşılıyor.', true, 'migration', null),
  ('ana-fikir-07', 'main_idea', 'medium', '6-7', 'Bir deneyin sonucunu önceden tahmin etmek, öğrenciyi gözlem yapmaya hazırlar. Tahmin doğru çıkmasa bile öğrenci hangi düşüncesinin değiştiğini fark eder ve yeni kanıtlar üzerinden daha dikkatli bir açıklama kurar.', 'Parçanın ana fikri nedir? Cevabınızı metindeki kanıtlara dayandırınız.', '["Deneylerde yalnızca doğru tahminler önemlidir.","Tahminler, doğru çıkmasa bile öğrenme ve düşünme sürecini destekler.","Bilimsel çalışmalarda açıklama yapmak gereksizdir.","Öğrenciler deney sonucunu değiştirebilir.","Kanıtlar yalnızca öğretmenler için gereklidir."]'::jsonb, 1, 'Metin tahminin değerini sonucunun doğruluğuna değil, gözlem ve yeniden düşünme sürecine bağlıyor.', true, 'migration', null),
  ('ana-fikir-08', 'main_idea', 'medium', '6-7', 'Bir fotoğrafın etkileyici olması için pahalı bir makineye sahip olmak şart değildir. Işığın yönünü gözlemek, uygun anı beklemek ve görüntüdeki gereksiz ayrıntıları ayıklamak çoğu zaman daha belirleyicidir.', 'Yazarın vurguladığı ana düşünce nedir? Ana bağlantıyı ve yardımcı bilgileri ayırınız.', '["Pahalı makineler her fotoğrafı güzelleştirir.","Fotoğraf çekmek için yalnızca hızlı davranmak gerekir.","İyi fotoğraf, araçtan çok dikkat ve doğru seçimlerle oluşur.","Işık fotoğrafçılıkta önemsizdir.","Fotoğrafta ayrıntı ne kadar fazlaysa sonuç o kadar iyidir."]'::jsonb, 2, 'D seçeneği, araçtan bağımsız olarak ışık, zamanlama ve kadraj seçimlerinin önemini topluyor.', true, 'migration', null),
  ('ana-fikir-09', 'main_idea', 'hard', '6-7', 'Kıyıya bırakılan plastikler dalgalarla denize taşınabiliyor. Bu atıklar bazı canlılar tarafından yiyecek sanılıyor ve beslenme düzenlerini bozuyor. Sahili temiz tutmak, yalnızca güzel bir görüntü oluşturmak değil, deniz canlılarını korumak anlamına da geliyor.', 'Bu paragrafın ana fikri hangisidir? Paragrafın anlam akışını izleyiniz.', '["Plastikler yalnızca kıyıda kalır.","Deniz canlıları plastikleri kolayca ayırt eder.","Güzel bir sahil her zaman temizdir.","Sahil temizliği deniz canlılarının sağlığı için de gereklidir.","Dalgalar kıyıya zarar vermez."]'::jsonb, 3, 'İlk seçenek, plastiklerin canlılara etkisi ile sahil temizliği arasındaki temel bağlantıyı kuruyor.', true, 'migration', null),
  ('ana-fikir-10', 'main_idea', 'hard', '6-7', 'Bir şehrin müzeleri, geçmişte yaşamış insanların kullandığı eşyaları korur. Ziyaretçi bu eşyaların hangi koşullarda kullanıldığını öğrendiğinde tarih, ezberlenecek tarihler listesinden çıkar ve günlük hayatla ilişkilenen canlı bir bilgiye dönüşür.', 'Parçanın temel düşüncesi nedir? Verilen bilgilerden hareket ediniz.', '["Müzeler yalnızca eski eşya depolarıdır.","Tarih öğrenmek için bütün eşyalar satın alınmalıdır.","Ziyaretçiler müzelerde konuşmamalıdır.","Tarihte yalnızca önemli kişiler incelenir.","Müzeler, geçmişi günlük yaşamla ilişkilendirerek anlamayı kolaylaştırır."]'::jsonb, 4, 'C seçeneği, müzelerin eşyalar aracılığıyla tarihi günlük hayatla ilişkilendirme işlevini açıklıyor.', true, 'migration', null),
  ('ana-fikir-11', 'main_idea', 'hard', '6-7', 'Bir ekipte herkesin aynı fikirde olması, işlerin mutlaka iyi gideceği anlamına gelmez. Farklı öneriler dikkatle dinlendiğinde eksik noktalar görünür hâle gelir; önemli olan tartışmayı kişilere değil, çözüme yöneltmektir.', 'Paragrafın ana mesajı nedir? Metnin amacıyla uyumlu seçeneği bulunuz.', '["Farklı fikirler yapıcı biçimde değerlendirildiğinde ekip çalışmasını güçlendirir.","Ekiplerde tartışma olmamalıdır.","Aynı fikirde olmayan kişiler ekipten ayrılmalıdır.","Çözüm üretmek yalnızca yöneticinin görevidir.","İyi ekiplerde herkes aynı düşünür."]'::jsonb, 0, 'Metin, görüş ayrılığını sorun olarak değil, çözüm odaklı yürütüldüğünde eksikleri gösteren bir imkân olarak sunuyor.', true, 'migration', null),
  ('ana-fikir-12', 'main_idea', 'easy', '6-7', 'Bir alışkanlığı değiştirmek isteyen kişi, yalnızca kendine ‘artık yapmayacağım’ demekle yetinmeyebilir. Eski davranışı başlatan ortamı fark etmek, yerine küçük bir alternatif koymak ve ilerlemeyi takip etmek değişimi daha sürdürülebilir hâle getirir.', 'Bu paragrafın ana düşüncesi nedir? Soruyu parçanın tamamını düşünerek yanıtlayınız.', '["Alışkanlıklar bir günde değişir.","Alışkanlık değişimi, nedenleri fark edip uygulanabilir adımlar atmayı gerektirir.","İrade kullanmak alışkanlık değişiminde gereksizdir.","Bütün alışkanlıklar aynı yöntemle bırakılır.","İlerlemeyi takip etmek değişimi zorlaştırır."]'::jsonb, 1, 'E seçeneği, ortamı fark etme, alternatif koyma ve takip etme adımlarını birlikte özetliyor.', true, 'migration', null),
  ('yardimci-dusunce-01', 'supporting_idea', 'easy', '6-7', 'Okulda kurulan tohum takas köşesinde öğrenciler, yetiştirdikleri bitkilerden kalan tohumları küçük zarflara koydu. Zarfların üzerine bitkinin adı, ekim zamanı ve güneş ihtiyacı yazıldı. Böylece öğrenciler yalnızca tohum değil, deneyim de paylaşmış oldu.', 'Parçada aşağıdakilerden hangisine değinilmiştir? Metindeki temel ilişkiye göre yanıtlayınız.', '["Tohumların tamamı öğretmenler tarafından toplanmıştır.","Öğrenciler yalnızca çiçek yetiştirmiştir.","Zarflara bitkilerin bakım bilgileri yazılmıştır.","Takas köşesi yıl boyunca kapalı kalmıştır.","Bitkiler güneşsiz yetiştirilmiştir."]'::jsonb, 2, 'İlk seçenek metinde açıkça verilen bakım bilgilerini doğru aktarır; diğerleri parçayla uyuşmaz.', true, 'migration', null),
  ('yardimci-dusunce-02', 'supporting_idea', 'easy', '6-7', 'Bir öğrenci sunum hazırlarken önce güvenilir kaynakları inceledi, sonra önemli bilgileri kendi cümleleriyle not aldı. Sunum sırasında kullandığı kaynakların adını da belirtti. Bu çalışma, araştırmanın yalnızca bilgi toplamaktan ibaret olmadığını gösterdi.', 'Parçada aşağıdakilerden hangisi söylenmektedir? Parçanın verdiği bilgilere göre düşününüz.', '["Sunumda kaynak belirtmek gereksizdir.","Öğrenci hiçbir kaynak kullanmamıştır.","Sunum hazırlamak yalnızca ezber yapmayı gerektirir.","Bilgileri kendi cümleleriyle düzenlemek araştırma sürecinin bir parçasıdır.","Güvenilir kaynaklar araştırmayı zorlaştırır."]'::jsonb, 3, 'B seçeneği, öğrencinin bilgileri kendi cümleleriyle not almasını doğrudan karşılıyor.', true, 'migration', null),
  ('yardimci-dusunce-03', 'supporting_idea', 'medium', '6-7', 'Parktaki yağmur bahçesinde, suyu toprağa geçiren özel bitkiler yetiştiriliyordu. Şiddetli yağmurdan sonra suyun bir bölümü burada tutuluyor, sokaklardaki birikinti azalıyordu. Bahçıvanlar bu alanın düzenli bakım istediğini özellikle belirtiyordu.', 'Bu parçadan hangisine ulaşılabilir? Doğru seçeneği metnin bütünüyle karşılaştırınız.', '["Yağmur bahçeleri hiç bakım istemez.","Bu alanlar yalnızca süs amacıyla kurulmuştur.","Özel bitkiler yağmurda yaşayamaz.","Sokaklardaki bütün su bu alanlarda toplanır.","Yağmur bahçeleri su birikintilerini azaltmaya yardımcı olabilir."]'::jsonb, 4, 'C seçeneği, yağmur suyunun bir bölümünün tutulması ile sokaktaki birikintinin azalması arasındaki sonucu kurar.', true, 'migration', null),
  ('yardimci-dusunce-04', 'supporting_idea', 'medium', '6-7', 'Bir sınıfta öğrenciler, kullanılmayan kâğıtları iki yüzünü de kullanmak üzere ayrı bir kutuda biriktirdi. Kutunun yanına tek yüzü boş kâğıtların taslak çalışmalarında kullanılabileceği yazıldı. Bir ay sonunda yeni kâğıt tüketiminin azaldığı görüldü.', 'Parçadan aşağıdakilerden hangisi çıkarılamaz? Anlatılan durumun sonucunu dikkate alınız.', '["Bir ay sonunda bütün kâğıt kullanımı tamamen bitmiştir.","Kâğıdın iki yüzünü kullanmak tüketimi azaltabilir.","Taslak çalışmaları için kullanılmış kâğıtlardan yararlanılmıştır.","Sınıf, kâğıtları yeniden değerlendirmek için bir yöntem uygulamıştır.","Kutunun yanında kullanım amacı açıklanmıştır."]'::jsonb, 0, 'D seçeneği çıkarılamaz; metin tüketimin azaldığını söylüyor, tamamen bittiğini söylemiyor.', true, 'migration', null),
  ('yardimci-dusunce-05', 'supporting_idea', 'medium', '6-7', 'Mert, okul çıkışında arkadaşının çantasının yırtıldığını fark etti. Kendi yedek ipini verdi ve çantayı birlikte onardılar. Ertesi gün arkadaşı ipi geri getirirken yanında küçük bir not da bıraktı.', 'Parçada aşağıdakilerden hangisine değinilmiştir? Metindeki ayrıntıları birlikte değerlendiriniz.', '["Mert çantayı tek başına satın almıştır.","İki arkadaş bir sorunu birlikte çözmüştür.","Not, çantanın içine saklanmıştır.","Arkadaşlar okuldan önce buluşmuştur.","Yedek ip kullanılmamıştır."]'::jsonb, 1, 'İkinci seçenek, ip verme ve çantayı birlikte onarma ayrıntılarını doğru birleştiriyor.', true, 'migration', null),
  ('yardimci-dusunce-06', 'supporting_idea', 'medium', '6-7', 'Bir şehir kütüphanesi, sınav haftasında sessiz çalışma saatlerini uzattı. Ayrıca masaların yanına prizler ve su sebilleri yerleştirdi. Öğrenciler, özellikle akşam saatlerinde bu düzenlemeden yararlandı.', 'Bu parçadan hangisi çıkarılabilir? Yazarın vurgusunu göz önünde bulundurunuz.', '["Kütüphane sınav haftasında tamamen kapanmıştır.","Öğrenciler yalnızca sabahları çalışmıştır.","Çalışma ortamındaki küçük düzenlemeler öğrencilerin kullanımını artırabilir.","Su sebilleri kitap okumayı engeller.","Kütüphanelerde priz bulunamaz."]'::jsonb, 2, 'C seçeneği, uzatılan saatler ve eklenen imkânların öğrencilerin kullanımını artırdığı sonucunu çıkarır.', true, 'migration', null),
  ('yardimci-dusunce-07', 'supporting_idea', 'medium', '6-7', 'Bir doğa gözlem kulübü, her hafta aynı gölün kıyısında farklı kuşları kaydetti. Öğrenciler gözlemlerini fotoğrafla destekledi ve tarihleri not etti. Dönem sonunda hangi kuşların hangi aylarda görüldüğüne dair bir çizelge hazırladılar.', 'Parçada aşağıdakilerden hangisi söylenmektedir? Cevabınızı metindeki kanıtlara dayandırınız.', '["Gözlemler tek bir gün yapılmıştır.","Kuşların fotoğrafı çekilmemiştir.","Kulüp yalnızca gölün suyunu incelemiştir.","Öğrenciler gözlemlerden yararlanarak dönem sonunda çizelge oluşturmuştur.","Kuşlar her ay aynı sayıda görülmüştür."]'::jsonb, 3, 'D seçeneği, tarihli gözlemlerden dönem sonu çizelgesi hazırlanması bilgisini doğru verir.', true, 'migration', null),
  ('yardimci-dusunce-08', 'supporting_idea', 'hard', '6-7', 'Bir öğrenci, matematik sorularında yaptığı hataları küçük bir deftere yazmaya başladı. Hatanın nedenini ve doğru çözümde hangi adımın değiştiğini de ekledi. Birkaç hafta sonra benzer sorularda aynı yanlışı daha az yaptığını fark etti.', 'Bu parçadan hangisine ulaşılabilir? Ana bağlantıyı ve yardımcı bilgileri ayırınız.', '["Hatalar yazıldığında bütün sorular kolaylaşır.","Öğrenci matematik çalışmayı bırakmıştır.","Doğru çözümde hiçbir adım değişmez.","Defter yalnızca öğretmen için tutulmuştur.","Hataları incelemek, benzer yanlışları azaltmaya yardımcı olabilir."]'::jsonb, 4, 'C seçeneği, hata nedenlerini inceleme ile benzer yanlışların azalması arasındaki gözlenebilir sonucu açıklar.', true, 'migration', null),
  ('yardimci-dusunce-09', 'supporting_idea', 'hard', '6-7', 'Mahalledeki yaşlı bir komşu, eski oyunları çocuklara öğretmek için hafta sonu buluşmaları düzenledi. Çocuklar oyunların kurallarını öğrenirken komşuları da kendi çocukluğundan anılar anlattı. Buluşmalar, farklı yaş gruplarını aynı etkinlikte bir araya getirdi.', 'Parçadan aşağıdakilerden hangisi çıkarılamaz? Paragrafın anlam akışını izleyiniz.', '["Etkinlik yalnızca yetişkinlerin katılımına açıktır.","Buluşmalar farklı yaşları bir araya getirmiştir.","Çocuklar eski oyunların kurallarını öğrenmiştir.","Komşu, çocukluğuna ait anılar paylaşmıştır.","Buluşmalar hafta sonu yapılmıştır."]'::jsonb, 0, 'D seçeneği çıkarılamaz; metin çocukların da etkinlikte bulunduğunu açıkça gösteriyor.', true, 'migration', null),
  ('yardimci-dusunce-10', 'supporting_idea', 'easy', '6-7', 'Bir okul koridoruna öğrencilerin sorularını yazabileceği bir pano asıldı. Öğretmenler her hafta bu sorulardan birkaçını seçip kısa cevaplar ekledi. Zamanla öğrenciler, ders sırasında akıllarına gelen soruları ertelemeden yazmaya başladı.', 'Parçada aşağıdakilerden hangisine değinilmiştir? Verilen bilgilerden hareket ediniz.', '["Soruların tamamı aynı gün cevaplanmıştır.","Pano, öğrencilerin merak ettikleri konuları görünür kılmıştır.","Öğretmenler öğrencilerin sorularını toplamıştır.","Öğrenciler ders sırasında hiç soru sormamıştır.","Pano yalnızca duyurular için kullanılmıştır."]'::jsonb, 1, 'B seçeneği, öğrencilerin sorularını yazması ve meraklarını görünür hâle getirmesi ayrıntısına dayanır.', true, 'migration', null),
  ('yardimci-dusunce-11', 'supporting_idea', 'hard', '6-7', 'Bir spor kulübü, antrenman sonrasında oyuncuların yalnızca skorlarını değil, birbirlerine yaptıkları destekleri de değerlendirdi. Böylece savunmada arkadaşını uyaran ya da hata yapan arkadaşını cesaretlendiren oyuncular fark edildi.', 'Bu parçadan hangisine ulaşılabilir? Metnin amacıyla uyumlu seçeneği bulunuz.', '["Kulüp yalnızca kazanan oyuncuları önemser.","Skorlar antrenmandan sonra hiç konuşulmaz.","Takım içindeki olumlu davranışlar da performansın değerlendirilmesinde dikkate alınabilir.","Oyuncular birbirleriyle iletişim kuramaz.","Savunma çalışmaları gereksizdir."]'::jsonb, 2, 'C seçeneği, skor dışındaki destek davranışlarının ayrıca değerlendirildiği bilgisinden çıkarılır.', true, 'migration', null),
  ('yardimci-dusunce-12', 'supporting_idea', 'easy', '6-7', 'Bir öğrenci, şehirdeki tarihi binaları fotoğraflarken her binanın yapım tarihini ve kullanım amacını araştırdı. Fotoğrafları tek başına sergilemek yerine kısa bilgi kartlarıyla birlikte sundu. Böylece ziyaretçiler binaları yalnızca görüntüleriyle değil, öyküleriyle de tanıdı.', 'Parçada aşağıdakilerden hangisi söylenmektedir? Soruyu parçanın tamamını düşünerek yanıtlayınız.', '["Fotoğraflarda bilgi kartı kullanılmamıştır.","Binaların yalnızca dış görünüşü incelenmiştir.","Öğrenci hiçbir araştırma yapmamıştır.","Fotoğraflar, araştırma bilgileriyle desteklenerek sunulmuştur.","Ziyaretçiler sergiyi görmemiştir."]'::jsonb, 3, 'E seçeneği, fotoğrafların yapım tarihi ve kullanım bilgileriyle birlikte sunulmasını karşılıyor.', true, 'migration', null),
  ('cikarim-01', 'inference', 'easy', '6-7', 'Ece, ödev yaparken telefonunu çalışma masasından kaldırıp salondaki çekmeceye koyuyor. Masasına yalnızca gerekli kitapları getiriyor ve çalışmaya başlamadan önce yapacağı işleri kâğıda yazıyor.', 'Bu parçadan Ece ile ilgili hangi sonuca ulaşılabilir? Metindeki temel ilişkiye göre yanıtlayınız.', '["Ece ödev yapmayı sevmemektedir.","Ece bütün ödevlerini telefondan yapmaktadır.","Ece plansız çalışmayı tercih etmektedir.","Ece yalnızca salonda ders çalışır.","Ece, dikkatini korumak için çalışma ortamını düzenlemektedir."]'::jsonb, 4, 'Telefonu uzaklaştırması, gerekli eşyaları seçmesi ve işlerini yazması Ece’nin dikkatini korumaya çalıştığını gösterir.', true, 'migration', null),
  ('cikarim-02', 'inference', 'easy', '6-7', 'Arda, yağmur başlamadan önce balkonundaki saksıları duvarın altına çekti. Sonra toprağın çok ıslanıp ıslanmadığını kontrol etti ve pencereyi kapattı. Yağmur dindikten sonra bitkileri yeniden güneş alan yere koydu.', 'Bu parçadan Arda''nın hangi davranışı çıkarılabilir? Parçanın verdiği bilgilere göre düşününüz.', '["Bitkilerin hava koşullarından zarar görmemesi için önlem almaktadır.","Bitkileriyle hiç ilgilenmemektedir.","Yağmurda dışarı çıkmayı sevmektedir.","Saksıları tamamen kaldırmıştır.","Bitkilerin güneşe ihtiyacı olmadığını düşünmektedir."]'::jsonb, 0, 'Saksıları korunaklı yere çekmesi ve sonrasında yeniden yerleştirmesi, bitkileri hava koşullarına göre koruduğunu gösterir.', true, 'migration', null),
  ('cikarim-03', 'inference', 'medium', '6-7', 'Kulüp toplantısında herkes kendi önerisini anlattı. Deniz, arkadaşının fikrindeki eksik noktayı gösterirken önce onun güçlü yanını belirtti, sonra birlikte geliştirebilecekleri bir yol önerdi. Toplantı sonunda iki öneri birleştirildi.', 'Deniz''in iletişim biçimiyle ilgili hangi çıkarım yapılabilir? Doğru seçeneği metnin bütünüyle karşılaştırınız.', '["Eleştiriden kaçınmaktadır.","Farklı görüşleri yapıcı biçimde geliştirmeye çalışmaktadır.","Yalnızca kendi fikrinin kabul edilmesini istemektedir.","Toplantılarda konuşmamaktadır.","Arkadaşının fikrini tamamen reddetmiştir."]'::jsonb, 1, 'Güçlü yanı belirtip eksik noktaya çözüm önermesi, Deniz’in eleştiriyi geliştirme amacıyla yaptığını gösterir.', true, 'migration', null),
  ('cikarim-04', 'inference', 'medium', '6-7', 'Köydeki değirmenin yanında yıllardır duran taş oluğun içinden artık su akmıyordu. Çocuklar oluğun yukarısındaki kanalın yapraklarla dolduğunu fark etti. Kanal temizlenince su yeniden oluğa ulaştı.', 'Parçadan hangi sonuca ulaşılabilir? Anlatılan durumun sonucunu dikkate alınız.', '["Değirmen tamamen yıkılmıştır.","Taş oluk su taşımak için kullanılmaktadır.","Yapraklar suyun akışını engellemiş olabilir.","Çocuklar kanalı kullanmamıştır.","Su kaynağı kurumuştur."]'::jsonb, 2, 'Kanal temizlenince suyun geri gelmesi, akışın yapraklar tarafından engellenmiş olabileceğini düşündürür.', true, 'migration', null),
  ('cikarim-05', 'inference', 'medium', '6-7', 'Selin, arkadaşının doğum günü için hazırladığı resmi son anda değiştirmedi. Çünkü arkadaşının sade çizimleri sevdiğini biliyor ve resmi kendi beğenisine göre süslemek istemiyordu. Hediyeyi verirken arkadaşının yorumunu dikkatle dinledi.', 'Selin''in tutumuyla ilgili hangisi çıkarılabilir? Metindeki ayrıntıları birlikte değerlendiriniz.', '["Resim yapmayı sevmemektedir.","Hediyesini değiştirmeyi unutmuştur.","Kendi beğenisini herkesinkinden üstün görmektedir.","Arkadaşının zevkine saygı göstermektedir.","Arkadaşının yorumunu önemsememektedir."]'::jsonb, 3, 'Resmi değiştirmemesi ve arkadaşının yorumunu dinlemesi, onun zevkine saygı duyduğunu gösterir.', true, 'migration', null),
  ('cikarim-06', 'inference', 'medium', '6-7', 'Bir gölün çevresindeki kurbağa sesleri önceki yıllara göre azalmıştı. Öğrenciler suyun kenarında deterjan köpükleri gördü ve yakındaki atölyeden gelen giderin göle ulaştığını öğrendi. Gider kapatılıp kıyı temizlenince kurbağaların sayısı zamanla arttı.', 'Bu parçadan hangi sonuca ulaşılabilir? Yazarın vurgusunu göz önünde bulundurunuz.', '["Kurbağalar yalnızca geceleri yaşar.","Göl çevresindeki sesler ölçülememiştir.","Atölye gölden çok uzaktadır.","Kurbağaların sayısı kıyı temizliğiyle azalır.","Su kirliliği kurbağaların yaşamını olumsuz etkilemiş olabilir."]'::jsonb, 4, 'Köpüklerin görülmesi, giderin kapatılması ve kurbağaların artması su kirliliği ile yaşam arasındaki bağlantıyı düşündürür.', true, 'migration', null),
  ('cikarim-07', 'inference', 'medium', '6-7', 'Yusuf, grup çalışmasında zorlandığı bölümü arkadaşlarından saklamadı. Önce soruyu nasıl anladığını anlattı, sonra arkadaşlarının farklı çözüm yollarını karşılaştırdı. Sonunda kendi yöntemindeki eksik adımı fark edip çözümünü düzeltti.', 'Yusuf hakkında aşağıdakilerden hangisi çıkarılabilir? Cevabınızı metindeki kanıtlara dayandırınız.', '["Hatasını fark ettiğinde düşüncesini gözden geçirebilmektedir.","Yardım istemeyi başarısızlık saymaktadır.","Grup çalışmasında yalnız kalmayı tercih etmektedir.","Sadece kendi çözümünün doğru olduğuna inanır.","Soruyu arkadaşlarına çözdürmüştür."]'::jsonb, 0, 'Farklı yöntemleri karşılaştırıp eksik adımını düzeltmesi, Yusuf’un geri bildirime açık olduğunu gösterir.', true, 'migration', null),
  ('cikarim-08', 'inference', 'hard', '6-7', 'Bir kasabanın meydanındaki saat uzun zamandır çalışmıyordu. Belediye görevlileri saati onarmak için eski parçaları araştırırken meydanda toplanan kişiler kendi anılarını anlattı. Saat yeniden çalıştığında insanlar yalnızca zamanı değil, meydanın ortak geçmişini de hatırladı.', 'Bu parçadan hangi sonuca ulaşılabilir? Ana bağlantıyı ve yardımcı bilgileri ayırınız.', '["Saatin hiçbir tarihî değeri yoktur.","Eski bir eşya, insanlar arasında ortak anıların canlanmasını sağlayabilir.","Meydan yalnızca görevliler tarafından kullanılır.","İnsanlar saat çalışırken meydana gelmemiştir.","Saatin parçaları hiç araştırılmamıştır."]'::jsonb, 1, 'Onarım sırasında anıların paylaşılması, saatin ortak geçmişi hatırlatan bir sembol olduğunu düşündürür.', true, 'migration', null),
  ('cikarim-09', 'inference', 'hard', '6-7', 'Nehir kıyısındaki köprüden geçenler, korkuluğun bazı bölümlerinin paslandığını fark etti. Mahalle sakinleri fotoğraf çekip belediyeye bildirdi, ardından onarım tamamlanana kadar çocukların köprüye yalnız gitmemesi konusunda anlaştı.', 'Mahalle sakinleriyle ilgili hangi çıkarım yapılabilir? Paragrafın anlam akışını izleyiniz.', '["Köprünün onarılmasını istememişlerdir.","Çocukların köprüden geçmesini teşvik etmişlerdir.","Sorunu fark edip hem bildirim hem de geçici güvenlik önlemi almışlardır.","Paslanan bölümleri kendileri sökmüştür.","Köprüde hiç tehlike görmemişlerdir."]'::jsonb, 2, 'Fotoğrafla bildirim yapılması ve çocuklar için geçici kural konması, sakinlerin sorumlu davrandığını gösterir.', true, 'migration', null),
  ('cikarim-10', 'inference', 'easy', '6-7', 'Nisa, her sabah aynı otobüse biniyor ancak bir gün şoförün durakta bekleyen yaşlı bir yolcuyu fark ettiğini gördü. Şoför kapıyı kapatmak yerine birkaç saniye daha bekledi. Nisa, küçük bir dikkatin birinin yolculuğunu kolaylaştırabileceğini düşündü.', 'Nisa''nın düşüncesinden hangi sonuç çıkarılabilir? Verilen bilgilerden hareket ediniz.', '["Otobüsler her zaman geç kalır.","Şoför yaşlı yolcuyu tanımaktadır.","Nisa toplu taşımayı kullanmayı bırakmıştır.","Küçük bir özenli davranışın başkasına önemli kolaylık sağlayabileceğini düşünmektedir.","Yaşlı yolcu otobüse binememiştir."]'::jsonb, 3, 'Nisa’nın düşüncesi, şoförün birkaç saniyelik dikkatinin yolcunun işini kolaylaştırmasına dayanıyor.', true, 'migration', null),
  ('cikarim-11', 'inference', 'hard', '6-7', 'Bir bilim insanı, deneyinde beklediği sonucu elde edemedi. Verileri silmek yerine ölçüm araçlarını ve deney koşullarını yeniden kontrol etti. Daha sonra ilk tahmininin yanlış olduğunu kabul ederek yeni bir soru oluşturdu.', 'Bilim insanının tutumuyla ilgili hangi çıkarım yapılabilir? Metnin amacıyla uyumlu seçeneği bulunuz.', '["Başarısız sonucu gizlemeyi seçmiştir.","Sonuçları önceden değiştirmiştir.","Yeni soru sormayı gereksiz bulmaktadır.","Deney yapmaktan vazgeçmiştir.","Kanıtlarla karşılaşınca düşüncesini yeniden değerlendirebilmektedir."]'::jsonb, 4, 'Verileri koruması, koşulları kontrol etmesi ve tahminini değiştirmesi bilimsel tutarlılık gösterir.', true, 'migration', null),
  ('cikarim-12', 'inference', 'easy', '6-7', 'İrem, hafta boyunca kullanmadığı eşyaları bir kutuda biriktirdi. Hafta sonunda kutudaki eşyaları ‘başkasına yarayabilir’, ‘onarılabilir’ ve ‘dönüştürülebilir’ diye ayırdı. Kutudan çıkanların çoğunu çöpe atmak yerine farklı biçimlerde değerlendirdi.', 'İrem''in davranışından hangi sonuca ulaşılabilir? Soruyu parçanın tamamını düşünerek yanıtlayınız.', '["Tüketim kararlarının sonuçlarını düşünerek israfı azaltmaya çalışmaktadır.","Eşyalarını sınıflandırmadan atmaktadır.","Hiçbir eşyayı kullanmamaktadır.","Onarılabilecek eşyaları çöpe göndermektedir.","Dönüştürmeyi gereksiz görmektedir."]'::jsonb, 0, 'Eşyaları kullanım durumuna göre ayırması, İrem’in atıkların sonucunu düşünüp israfı azaltmaya çalıştığını gösterir.', true, 'migration', null),
  ('tamamlama-01', 'completion', 'easy', '6-7', 'Bir öğrenci, sabahları çantasına hangi kitapları koyacağını akşamdan belirlemeye başladı. Böylece aceleyle hazırlanırken defterlerini evde unutma sorunu azaldı. _____', 'Paragraf aşağıdakilerden hangisiyle tamamlanırsa anlam bütünlüğü sağlanır? Metindeki temel ilişkiye göre yanıtlayınız.', '["Bu nedenle bütün kitaplar aynı anda okunmalıdır.","Önceden yapılan küçük hazırlıklar, güne daha düzenli başlamaya yardım eder.","Çantalar yalnızca okulda hazırlanır.","Unutmak her öğrencinin değişmez özelliğidir.","Sabahları hazırlık yapmak her zaman daha uzun sürer."]'::jsonb, 1, 'Son cümle, akşamdan yapılan hazırlığın unutmayı azaltmasıyla bağ kurup genel sonucu çıkarıyor.', true, 'migration', null),
  ('tamamlama-02', 'completion', 'easy', '6-7', 'Mahalledeki boş arsa, yıllarca yalnızca toz ve taşlarla kaplıydı. Sakinler burada küçük bir oyun alanı yapmak için belediyeye başvurdu ve ağaç dikme planı hazırladı. _____', 'Bu paragraf hangi cümleyle tamamlanmalıdır? Parçanın verdiği bilgilere göre düşününüz.', '["Arsa daha sonra yine kullanılmadan bırakıldı.","Çocuklar oyun alanlarının hepsini sevmez.","Ortak bir istek, kullanılmayan bir alanın mahalle için yararlı hâle gelmesini sağlayabilir.","Ağaçların çoğu yalnızca ormanda yetişir.","Belediye başvurulara hiçbir zaman cevap vermez."]'::jsonb, 2, 'Yeni cümle, sakinlerin başvuru ve planından beklenen sonucu doğal biçimde tamamlıyor.', true, 'migration', null),
  ('tamamlama-03', 'completion', 'easy', '6-7', 'Bir müzik grubunda herkes aynı anda çalmaya çalışınca ortaya karmaşık bir ses çıktı. Öğretmen, her öğrencinin eser içindeki görevini belirledi ve dinleme işaretleri ekledi. _____', 'Paragrafın devamı aşağıdakilerden hangisi olmalıdır? Doğru seçeneği metnin bütünüyle karşılaştırınız.', '["Bütün öğrenciler müzik aletlerini bıraktı.","Eserin adı hiçbir zaman öğrenilmedi.","Dinleme işaretleri yalnızca resimlerde kullanılır.","Böylece grup, birbirini dinleyerek daha uyumlu çalmaya başladı.","Grup çalışmaları tek başına yapılır."]'::jsonb, 3, 'Görev paylaşımı ve dinleme işaretlerinin doğal sonucu, grubun daha uyumlu çalmasıdır.', true, 'migration', null),
  ('tamamlama-04', 'completion', 'medium', '6-7', 'Bir sınıf, gezide gördüğü tarihi yapılar hakkında kısa bilgi kartları hazırladı. Kartlarda yapının adı, yaşı ve dikkat çeken özelliği yer aldı. Ziyaretçiler kartları okuyarak yapıları daha kolay tanıdı. _____', 'Paragraf aşağıdakilerden hangisiyle tamamlanır? Anlatılan durumun sonucunu dikkate alınız.', '["Bilgi kartları yapıların fotoğrafını yok etti.","Tarihi yapılar artık hiç ziyaret edilmedi.","Öğrenciler kartları evde sakladı.","Gezilerde bilgi kullanmak gereksizdir.","Bu çalışma, geziyi yalnızca görmekten çıkarıp araştırmaya dayalı bir öğrenmeye dönüştürdü."]'::jsonb, 4, 'Son cümle, kart hazırlama ve ziyaretçilerin öğrenmesi arasındaki eğitimsel sonucu tamamlıyor.', true, 'migration', null),
  ('tamamlama-05', 'completion', 'medium', '6-7', 'Bir aile, evdeki kullanılmayan kavanozları atmak yerine temizleyip mutfakta yeniden kullanmaya başladı. Kavanozların üzerine içindeki ürünün adı ve tarihi yazıldı. _____', 'Bu paragraf aşağıdakilerden hangisiyle tamamlanırsa anlam bütünlüğü sağlanır? Metindeki ayrıntıları birlikte değerlendiriniz.', '["Böylece hem yeni kap alma ihtiyacı azaldı hem de düzen sağlandı.","Kavanozlar yalnızca süs eşyası olarak kaldı.","Mutfakta hiçbir ürün saklanamaz.","Etiketler kavanozların kullanımını engelledi.","Aile bütün eşyalarını çöpe attı."]'::jsonb, 0, 'Yeniden kullanım ve etiketleme, ihtiyaç azaltma ve düzen sonucuna bağlanıyor.', true, 'migration', null),
  ('tamamlama-06', 'completion', 'medium', '6-7', 'Bir öğrenci, yazdığı öykünün ilk taslağını arkadaşına okuttu. Arkadaşı olayların bir bölümünün hızlı geçtiğini ve bazı kişilerin neden karar verdiğinin anlaşılmadığını söyledi. Öğrenci taslağı yeniden düzenledi. _____', 'Paragrafın son cümlesi hangisi olmalıdır? Yazarın vurgusunu göz önünde bulundurunuz.', '["Öykülerde karakterlerin kararları önemli değildir.","Bu geri bildirim, öykünün olay ve karakter bağlantılarını güçlendirdi.","Arkadaşının önerileri metnin okunmasını zorlaştırdı.","İlk taslak her zaman son hâlden iyidir.","Öykü yeniden okunmadan yayımlandı."]'::jsonb, 1, 'Sorunların belirtilmesi ve metnin yeniden düzenlenmesi, bağlantıların güçlenmesi sonucunu doğurur.', true, 'migration', null),
  ('tamamlama-07', 'completion', 'medium', '6-7', 'Okulun su sebillerinin yanında öğrencileri kendi mataralarını getirmeye teşvik eden bir duyuru asıldı. Bir süre sonra sınıflarda tek kullanımlık bardakların azaldığı görüldü. _____', 'Paragraf aşağıdakilerden hangisiyle tamamlanmalıdır? Cevabınızı metindeki kanıtlara dayandırınız.', '["Mataralar yalnızca spor salonunda kullanılır.","Duyurular hiçbir davranışı etkileyemez.","Küçük bir hatırlatma, çevreye yönelik bir alışkanlığın yayılmasına katkı sağlayabilir.","Bardakların sayısı bütün okullarda aynıdır.","Sebiller kullanılmadan kaldırıldı."]'::jsonb, 2, 'Duyuru ile bardak kullanımındaki azalma arasındaki ilişki, davranış alışkanlığındaki değişimi tamamlıyor.', true, 'migration', null),
  ('tamamlama-08', 'completion', 'hard', '6-7', 'Bir kasaba, yağmur suyu depolamak için evlerin çatılarından gelen suyu ortak bir depoda biriktirmeye başladı. Depodaki su bahçe sulamada kullanıldı; içme suyu ise ayrı tutuldu. _____', 'Bu paragrafın anlam bütünlüğünü sağlayan cümle hangisidir? Ana bağlantıyı ve yardımcı bilgileri ayırınız.', '["Kasabada bütün çatılar kaldırıldı.","Bahçe sulamak artık tamamen yasaklandı.","Yağmur suyu her durumda içilebilir.","Böylece içme suyunu gereksiz yere bahçe sulamada kullanma ihtiyacı azaldı.","Depo yalnızca kışın boş kaldı."]'::jsonb, 3, 'İçme suyunun ayrı tutulması, depolanan suyun bahçe için kullanılmasıyla kaynak tasarrufu sonucuna bağlanır.', true, 'migration', null),
  ('tamamlama-09', 'completion', 'hard', '6-7', 'Bir öğrenci, yeni öğrendiği yabancı kelimeleri yalnızca liste hâlinde ezberlemek yerine kendi cümlelerinde kullanmaya başladı. Bazı cümleleri arkadaşlarıyla konuşurken tekrar etti. _____', 'Paragraf aşağıdakilerden hangisiyle tamamlanır? Paragrafın anlam akışını izleyiniz.', '["Kelimeler konuşmada hiç kullanılmadı.","Yabancı dil öğrenmek yalnızca sözlüğe bakmaktır.","Arkadaşları cümleleri anlamadı.","Kelime listeleri tamamen kaldırıldı.","Bu yöntem, kelimelerin anlamını bağlam içinde hatırlamasını kolaylaştırdı."]'::jsonb, 4, 'Kelimeyi cümlede ve konuşmada kullanmak, anlamı bağlama bağlayarak hatırlamayı kolaylaştırır.', true, 'migration', null),
  ('tamamlama-10', 'completion', 'hard', '6-7', 'Bir tiyatro kulübü oyunun dekorunu hazırlarken karton kutuları, eski kumaşları ve kullanılmayan boyaları değerlendirdi. Öğrenciler önce sahnenin ihtiyaçlarını listeledi, sonra ellerindeki malzemeleri bu listeye göre seçti. _____', 'Bu paragraf hangi cümleyle tamamlanmalıdır? Verilen bilgilerden hareket ediniz.', '["Böylece hem malzeme israfını azalttılar hem de yaratıcı bir dekor oluşturdular.","Dekor çalışması plansız biçimde yarıda kaldı.","Tiyatroda dekor kullanmak yasaktır.","Eski kumaşlar hiçbir işe yaramadı.","Öğrenciler oyunu sahnesiz oynadı."]'::jsonb, 0, 'İhtiyaç listesiyle malzeme seçmek, hem israfı azaltan hem yaratıcı üretimi destekleyen sonuca götürüyor.', true, 'migration', null),
  ('tamamlama-11', 'completion', 'easy', '6-7', 'Bir okul, teneffüslerde koridorların çok gürültülü olduğunu fark etti. Öğrencilerle birlikte sessiz alanlar belirledi ve bu alanların kullanım kurallarını panoya astı. _____', 'Paragrafın sonuna hangisi getirilmelidir? Metnin amacıyla uyumlu seçeneği bulunuz.', '["Bütün öğrenciler teneffüslerde sınıfta kaldı.","Kuralların açıklanması, öğrencilerin farklı ihtiyaçlara göre alan seçmesini kolaylaştırdı.","Gürültü sorununu çözmek için bütün panolar kaldırıldı.","Sessiz alanlarda konuşmak tamamen yasaklandı.","Koridorlar artık hiç kullanılmadı."]'::jsonb, 1, 'Sessiz alanların belirlenmesi ve kuralların açıklanması, alan seçimini kolaylaştıran sonuca bağlanır.', true, 'migration', null),
  ('tamamlama-12', 'completion', 'medium', '6-7', 'Bir çocuk, balkonunda gördüğü kelebeklerin hangi bitkilerin çevresinde daha çok bulunduğunu not etti. Birkaç hafta sonra bazı bitkilerin kelebekleri çektiğini fark etti ve gözlemlerini çizimlerle destekledi. _____', 'Paragraf aşağıdakilerden hangisiyle tamamlanmalıdır? Soruyu parçanın tamamını düşünerek yanıtlayınız.', '["Gözlemlerini bırakıp bütün bitkileri söktü.","Kelebeklerin bitkilerle hiçbir ilişkisi yoktu.","Bu çalışma, merakın düzenli gözlemle küçük bir araştırmaya dönüşebileceğini gösterdi.","Çizimler gözlem yapmayı engelledi.","Çocuk yalnızca kelebeklerin rengini sordu."]'::jsonb, 2, 'Not alma, karşılaştırma ve çizim yapma adımları gözlemin küçük bir araştırmaya dönüştüğünü gösterir.', true, 'migration', null),
  ('akis-01', 'flow', 'easy', '6-7', '(I) Okulun bahçesine yeni banklar yerleştirildi. (II) Öğrenciler teneffüslerde bu banklarda kitap okumaya başladı. (III) Bankların çevresine gölge sağlayan fidanlar dikildi. (IV) Kış aylarında bazı bölgelerde kar yağışı görülebilir. (V) Böylece bahçede dinlenmek için daha kullanışlı alanlar oluştu.', 'Akışı bozan cümle hangisidir? Metindeki temel ilişkiye göre yanıtlayınız.', '["I","II","III","IV","V"]'::jsonb, 3, 'IV. cümle kar yağışından söz ederek bahçedeki bank ve fidanların işlevini anlatan akışı kesiyor.', true, 'migration', null),
  ('akis-02', 'flow', 'easy', '6-7', '(I) Bir araştırmacı önce gözlemlemek istediği canlıyı belirledi. (II) Gözlem saatlerini ve kullanacağı araçları planladı. (III) Araştırma defterinin kapağını mavi renge boyadı. (IV) Her gözlemden sonra bulgularını tarihleriyle yazdı. (V) Dönem sonunda notlarını karşılaştırarak bir sonuca ulaştı.', 'Numaralanmış cümlelerden hangisi düşünce akışını bozmaktadır? Parçanın verdiği bilgilere göre düşününüz.', '["I","II","IV","V","III"]'::jsonb, 4, 'III. cümle defterin kapağının rengini anlatıyor; diğer cümleler araştırma sürecinin adımlarını izliyor.', true, 'migration', null),
  ('akis-03', 'flow', 'easy', '6-7', '(I) Mahalle sakinleri boş arsayı temizledi. (II) Alana sebze yetiştirmek için bölümler ayırdılar. (III) Her bölümden sorumlu kişiyi belirlediler. (IV) Mahalledeki apartmanların çoğu dört katlıdır. (V) Ürünleri ihtiyaç sahipleriyle paylaşmaya karar verdiler.', 'Akışı bozan cümle hangisidir? Doğru seçeneği metnin bütünüyle karşılaştırınız.', '["IV","I","II","III","V"]'::jsonb, 0, 'IV. cümle apartmanların kat sayısını vererek ortak bahçe kurma sürecinin dışına çıkıyor.', true, 'migration', null),
  ('akis-04', 'flow', 'medium', '6-7', '(I) Bir öğrenci sunumuna başlık ve amaç bilgisiyle başladı. (II) Konuyu destekleyen görseller kullandı. (III) Sunumdan sonra sınıftaki perdeler yıkandı. (IV) Önemli noktaları kısa cümlelerle açıkladı. (V) Sonunda dinleyicilerin sorularını yanıtladı.', 'Paragrafın akışını bozan cümle hangisidir? Anlatılan durumun sonucunu dikkate alınız.', '["I","III","II","IV","V"]'::jsonb, 1, 'III. cümle sınıf perdesinin yıkanmasını anlatıyor; diğerleri sunumun hazırlanması ve yapılmasıyla ilgili.', true, 'migration', null),
  ('akis-05', 'flow', 'medium', '6-7', '(I) Arılar çiçeklerden nektar toplar. (II) Topladıkları nektarı kovana taşırlar. (III) Kovandaki bazı arılar nektarı işler. (IV) Balın tadı, tüketildiği ülkeye göre değişebilir. (V) Böylece koloni için besin depolanır.', 'Paragrafın akışını bozan cümle hangisidir? Metindeki ayrıntıları birlikte değerlendiriniz.', '["I","II","IV","III","V"]'::jsonb, 2, 'IV. cümle balın tadını ülkeler üzerinden anlatıyor; diğer cümleler arıların nektar işleme sürecini açıklıyor.', true, 'migration', null),
  ('akis-06', 'flow', 'medium', '6-7', '(I) Bir müzisyen yeni parçayı önce yavaş tempoda çaldı. (II) Zorlandığı ölçüleri ayrı ayrı tekrar etti. (III) Konser salonunun koltukları kırmızı renkteydi. (IV) Hataları azaldıkça tempoyu artırdı. (V) Son provada parçayı baştan sona çalmayı denedi.', 'Numaralı cümlelerden hangisi akışı bozmaktadır? Yazarın vurgusunu göz önünde bulundurunuz.', '["I","II","IV","III","V"]'::jsonb, 3, 'III. cümle salonun koltuk rengini veriyor; diğer cümleler parçayı öğrenme aşamalarını anlatıyor.', true, 'migration', null),
  ('akis-07', 'flow', 'medium', '6-7', '(I) Bir kasaba, eski tren istasyonunu kültür merkezine dönüştürdü. (II) Bekleme salonunda yerel sanatçıların eserleri sergilendi. (III) İstasyonun çatısı iki yıl önce yenilenmişti. (IV) Eski bilet gişesi okuma köşesi olarak düzenlendi. (V) Böylece yapı hem korundu hem de halka açık yeni bir işlev kazandı.', 'Akışı bozan cümle hangisidir? Cevabınızı metindeki kanıtlara dayandırınız.', '["I","II","IV","V","III"]'::jsonb, 4, 'III. cümle çatının geçmişte yenilenmesini söylüyor; diğerleri kültür merkezine dönüşümün yeni işlevlerini sıralıyor.', true, 'migration', null),
  ('akis-08', 'flow', 'hard', '6-7', '(I) Öğrenciler okul gezisi için yanlarına su mataraları aldı. (II) Öğretmen gezi boyunca çöplerin ayrı toplanmasını istedi. (III) Öğrenciler yürüyüş sırasında farklı ağaç türlerini gözlemledi. (IV) Okulun spor salonu geçen yıl boyandı. (V) Dönüşte herkes getirdiği atığı uygun kutuya bıraktı.', 'Düşünce akışını bozan cümle hangisidir? Ana bağlantıyı ve yardımcı bilgileri ayırınız.', '["IV","I","II","III","V"]'::jsonb, 0, 'IV. cümle spor salonunun boyanmasını anlatıyor; diğerleri doğa gezisindeki çevre davranışlarıyla bağlantılı.', true, 'migration', null),
  ('akis-09', 'flow', 'hard', '6-7', '(I) Bir yazar karakterinin kararlarını belirlemeden önce onun geçmişini düşündü. (II) Karakterin korkularını ve hedeflerini not aldı. (III) Romanın ilk baskısı küçük bir yayınevinde yapılmıştı. (IV) Daha sonra olay örgüsünü bu özelliklere göre kurdu. (V) Böylece karakterin davranışları metin boyunca tutarlı kaldı.', 'Paragrafın akışını bozan cümle hangisidir? Paragrafın anlam akışını izleyiniz.', '["I","III","II","IV","V"]'::jsonb, 1, 'III. cümle romanın yayınevi bilgisini veriyor; diğerleri karakter oluşturma ve tutarlılıkla ilgili.', true, 'migration', null),
  ('akis-10', 'flow', 'easy', '6-7', '(I) Bir öğrenci sabah yapacağı işleri akşamdan listeledi. (II) Öncelikli işlerinin yanına küçük bir işaret koydu. (III) Çalışma masasının ahşap yüzeyini bezle sildi. (IV) Sabah ilk olarak öncelikli işine başladı. (V) Gün sonunda tamamladıklarını kontrol etti.', 'Akışı bozan cümle hangisidir? Verilen bilgilerden hareket ediniz.', '["I","II","III","IV","V"]'::jsonb, 2, 'III. cümle masa temizliğini anlatıyor; diğerleri zaman planlama ve takip adımlarını sürdürüyor.', true, 'migration', null),
  ('akis-11', 'flow', 'hard', '6-7', '(I) Bir veteriner, barınaktaki köpeklerin davranışlarını gözlemledi. (II) Korkak olanların yanına önce sessizce oturdu. (III) Bazı köpeklerin tüyleri kahverengi ve beyazdı. (IV) Zamanla köpekler veterinerin yaklaşımına alıştı. (V) Daha sonra onları yeni ailelerle tanıştırmak kolaylaştı.', 'Numaralı cümlelerden hangisi akışı bozmaktadır? Metnin amacıyla uyumlu seçeneği bulunuz.', '["I","II","IV","III","V"]'::jsonb, 3, 'III. cümle tüy renklerini söylüyor; diğerleri veterinerin güven oluşturma sürecini anlatıyor.', true, 'migration', null),
  ('akis-12', 'flow', 'medium', '6-7', '(I) Bir ekip, okul gazetesi için röportaj konusu seçti. (II) Sorularını konuğun yaşına ve deneyimine uygun hazırladı. (III) Gazetenin son sayısında spor haberleri daha geniş yer tuttu. (IV) Röportaj sırasında cevapları dikkatle not aldı. (V) Yazıyı yayımlamadan önce konuğa doğrulatmayı kararlaştırdı.', 'Paragrafın düşünce akışını bozan cümle hangisidir? Soruyu parçanın tamamını düşünerek yanıtlayınız.', '["I","II","IV","V","III"]'::jsonb, 4, 'III. cümle spor haberlerinin sayfa dağılımını anlatıyor; diğerleri röportaj hazırlığı ve doğrulamasıyla ilgili.', true, 'migration', null)
on conflict (id) do nothing;
