/* eslint-disable @typescript-eslint/no-explicit-any */
import OpenAI from "openai";
import { NextResponse, type NextRequest } from "next/server";
import { getAdminSessionFromCookies, isAdminSessionValid } from "@/lib/auth/adminSession";
import { listQuestions, validateQuestionInput, type QuestionInput } from "@/lib/paragraph-exercises/paragraphQuestionAdminRepository";

export const runtime = "nodejs";
const active = new Set<string>();
const C = ["main_idea", "supporting_idea", "inference", "completion", "flow"] as const;
const G = ["4-5", "6-7", "8", "high-school"] as const;
const D = ["easy", "medium", "hard"] as const;
const schema = { type: "object", additionalProperties: false, required: ["questions"], properties: { questions: { type: "array", minItems: 1, maxItems: 10, items: { type: "object", additionalProperties: false, required: ["category", "difficulty", "gradeBand", "passage", "question", "options", "correctIndex", "explanation"], properties: { category: { type: "string", enum: [...C] }, difficulty: { type: "string", enum: [...D] }, gradeBand: { type: "string", enum: [...G] }, passage: { type: "string" }, question: { type: "string" }, options: { type: "array", minItems: 5, maxItems: 5, items: { type: "string" } }, correctIndex: { type: "integer", minimum: 0, maximum: 4 }, explanation: { type: "string" } } } } } } as const;
const fail = (error: string, status: number) => NextResponse.json({ ok: false, error }, { status });
const rec = (v: unknown): v is Record<string, unknown> => typeof v === "object" && v !== null && !Array.isArray(v);
const norm = (v: string) => v.normalize("NFKC").toLocaleLowerCase("tr-TR").replace(/\s+/gu, " ").trim();
function parse(v: unknown, r: any): QuestionInput[] | null { if (!rec(v) || !Array.isArray(v.questions) || v.questions.length !== r.questionCount) return null; const out: QuestionInput[] = []; for (const x of v.questions) { if (!rec(x) || x.category !== r.category || x.difficulty !== r.difficulty || x.gradeBand !== r.gradeBand) return null; const y = validateQuestionInput(x); if (!y.ok) return null; out.push(y.value); } return out; }
function prompt(r: any) { const rule = r.category === "main_idea" ? "Bütün paragrafı ölç, tek ayrıntıyı ana fikir yapma." : r.category === "supporting_idea" ? "Destekleyici ayrıntıyı ölç, ana fikir sorusuna dönüşmesin." : r.category === "inference" ? "Doğru cevap paragrafta birebir yazılı olmasın, mantıksal olarak çıkarılsın." : r.category === "completion" ? "Eksik cümle anlam akışını tamamlasın." : "Beş numaralı cümle (I)-(V) formatı kullan; options yalnız I/II/III/IV/V olsun ve correctIndex bozan cümleyi göstersin."; return `Türkçe öğretmeni gibi ${r.questionCount} paragraf sorusu üret. Tam 5 seçenek, tek açık doğru, makul distractorlar, seçeneklerde A) prefixi/hepsi/hiçbiri olmasın. Doğru indeksleri 0-4 arasında dengeli dağıt. ${rule} Seviye ${r.gradeBand}, kategori ${r.category}, zorluk ${r.difficulty}, uzunluk ${r.length}, konu ${r.topic}, ek talimat ${r.customInstruction || "yok"}. Yalnız JSON schema döndür.`; }
async function call(o: OpenAI, r: any) { return o.responses.create({ model: process.env.OPENAI_CONTENT_MODEL ?? process.env.OPENAI_ANALYSIS_MODEL ?? "gpt-5-mini", store: false, instructions: prompt(r), input: r.topic, max_output_tokens: 9000, text: { format: { type: "json_schema", name: "paragraph_question_batch", strict: true, schema: { ...schema, properties: { questions: { ...schema.properties.questions, minItems: r.questionCount, maxItems: r.questionCount } } } } } }); }
export async function POST(req: NextRequest) { if (!isAdminSessionValid(req)) return fail("Yetkisiz erişim.", 401); let b: unknown; try { b = await req.json(); } catch { return fail("Üretim bilgilerini kontrol edin.", 400); } if (!rec(b) || !C.includes(b.category as never) || !G.includes(b.gradeBand as never) || !D.includes(b.difficulty as never) || typeof b.topic !== "string" || b.topic.trim().length < 3 || b.topic.length > 160 || typeof b.customInstruction !== "string" || b.customInstruction.length > 500 || !Number.isInteger(b.questionCount) || Number(b.questionCount) < 1 || Number(b.questionCount) > 10 || !(["short", "medium", "long"] as string[]).includes(String(b.length))) return fail("Üretim bilgilerini kontrol edin.", 400); const r = { category: String(b.category), gradeBand: String(b.gradeBand), difficulty: String(b.difficulty), topic: b.topic.trim(), customInstruction: b.customInstruction.trim(), questionCount: Number(b.questionCount), length: String(b.length) }; const key = getAdminSessionFromCookies(req)?.trim(); if (!key) return fail("Yetkisiz erişim.", 401); if (active.has(key)) return fail("Bu öğretmen için üretim zaten devam ediyor.", 429); if (!process.env.OPENAI_API_KEY?.trim()) return fail("AI yapılandırması eksik.", 500); active.add(key); try { const o = new OpenAI({ apiKey: process.env.OPENAI_API_KEY.trim() }); let out = await call(o, r), parsed: unknown; try { parsed = JSON.parse(out.output_text ?? ""); } catch { return fail("Sorular oluşturulamadı. Lütfen tekrar deneyin.", 502); } let qs = parse(parsed, r); if (!qs) { out = await call(o, { ...r, customInstruction: `Geçersiz çıktı oluştu. Tüm şema ve kalite kurallarına uy. ${r.customInstruction}` }); try { parsed = JSON.parse(out.output_text ?? ""); } catch { return fail("Sorular oluşturulamadı. Lütfen tekrar deneyin.", 502); } qs = parse(parsed, r); } if (!qs) return fail("Üretilen bazı sorular kalite kontrolünden geçmedi.", 502); const existing = await listQuestions({ page: 1, pageSize: 100, category: r.category, difficulty: r.difficulty, gradeBand: r.gradeBand }); const seen = new Set(existing.items.flatMap(q => [norm(q.paragraph), norm(q.question)])); return NextResponse.json({ ok: true, questions: qs, duplicateFlags: qs.map(q => seen.has(norm(q.passage)) || seen.has(norm(q.question))) }); } catch (e) { console.error("paragraph_question_generation_failed", e); return fail("Sorular oluşturulamadı. Lütfen tekrar deneyin.", 502); } finally { active.delete(key); } }
